### ISSUE TITLE
Wrong UI elements in group listing presented to non-member

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#100]
- [x] Add to an appropriate Epic.

Tester (if different from issue creator): Anne
Site: UP Commons
URL: https://up.hcommons-dev.org/groups/
Test Account: Ferdinand Test
Area (CORE, sites, profiles, groups, general): groups
If issue discovered on dev, does it also exist on prod? Not tested

**Describe the issue**
When user is not member of a society, Ferdinand Test is seeing a mix of red and greyed out buttons, both Join and Request membership for the Birds of a Feather group. (A UP tester should check if they see Request Membership instead of or in addition to Join.) Weirdly, last time I checked this, using the previous registration of Ferdinand on Firefox, I only saw grey buttons. This time I'm on Chrome. When I click join as a non-member it just hangs, there's a circle animation. 

In the console: 
```
jquery.js?ver=3.5.1:4055 Uncaught TypeError: $(...).live is not a function
    at HTMLDocument.<anonymous> (autoptimize_ad85c7a1d1fbd8a2dea7542d77e0d27d.php:262)
    at mightThrow (jquery.js?ver=3.5.1:3762)
    at process (jquery.js?ver=3.5.1:3830)
(anonymous) @ autoptimize_ad85c7a1d1fbd8a2dea7542d77e0d27d.php:262
mightThrow @ jquery.js?ver=3.5.1:3762
process @ jquery.js?ver=3.5.1:3830
/wp-admin/admin-ajax.php:1 Failed to load resource: the server responded with a status of 403 ().
```
       
This may be a birds of a feather/UP specific problem. SAH groups look as expected.

**Comment by mikethicke** [comment]
Shows for test user:

![Screen Shot 2021-08-30 at 3.48.20 PM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/8173d1be-9032-4a48-afaa-d4714c15217b)

From Eric:
> A  'Birds of a Feather' group in this case may refer specifically to UP Commons private groups with special join logic. There is a custom membership setting which enables auto-join for private groups with certain attributes set. Only UP Commons members should be able to join and the request membership workflow is automated to allow any UP Commons member to join the group. Outside of that, normal "private group" rules apply.

**Comment by mikethicke** [comment]
This issue exists on prod:

![Screen Shot 2021-08-30 at 3.52.25 PM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/cc804658-d020-4fa7-b639-f472e8720169)

Clicking join group triggers the in-progress animation and doesn't do anything beyond that.

**Comment by mikethicke** [comment]
Fix ready for testing. See: https://github.com/MESH-Research/hc-custom/pull/156

**Comment by bjr70** [comment]
Fixed!

**Comment by bjr70** [comment]
Fixed.
