### ISSUE TITLE
Remove deposit by Jim Harries from CORE

### ISSUE THREAD

**Issue by katknow** [MESH-Research/commons#102]
- [x] Add to an appropriate Epic

Date first reported: 8/30/21
Date requested for completion:
Site: Humanities Commons
Area (CORE, profiles, sites, groups, account ): CORE

**Description**
User Jim Harries uploaded a book cover as an advertisement and needs to be removed from CORE. Deposit titled "How Western Anti-Racism Harms Africa and How we can do Better."

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
COmanage:  https://registry.hcommons.org/registry/co_people/canvas/124202 WP: https://hcommons.org/members/jimoharries/

**Trello link (if moved from Trello)**

**Comment by bjr70** [comment]
@mikethicke I'm not entirely sure what the process is to remove CORE deposits. Have you done this yet? We may need to loop Eric in to document this process.

**Comment by ericknappe** [comment]
This one has been removed. This process is complicated.
