### ISSUE TITLE
Members page has new ellipsis and blank item

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#108]
- [x] Add to an appropriate Epic.

Tester (if different from issue creator): Bonnie
Site: hcommons dev
URL: https://hcommons-dev.org/members/
Test Account: bonnie, Diana Test, Dave Test
Area (CORE, sites, profiles, groups, general): Members
If issue discovered on dev, does it also exist on prod? No

**Describe the issue**
The members page has some changes due to the upgrade. The following tab no longer appears for users, and the superadmin shows an ellipsis with a blank menu item when clicked. See screenshots.

**To Reproduce**

**Expected behavior**

**Screenshots**
![members_prod.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/16d63582-109d-47e7-bdaf-7517744fd299)
![members_superadmin.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/5685eb82-3bb9-412e-b3b0-41ece98af045)
![members.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/240bb879-1cdb-4cb4-9d2e-9190374fdf34)

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
I'm having trouble replicating this one. Can you confirm that it is still occurring for you? What OS/browser are you on?

**Comment by bjr70** [comment]
This is no longer happening. I think this was pre-updates.
