### ISSUE TITLE
Updating zotpress resets user settings

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#110]
- [x] Add to an appropriate Epic.

URL: https://scholarlytales.hcommons.org/
Area (CORE, sites, profiles, groups, general): sites

**Describe the issue**
Updating zotpress plugin (and possibly changing themes) wipes user settings.

**Additional context**
Previous notes:

>- The Scholarly Tales (zotpress)
	- possibly relevant: [Warning for “major updates in this version of Zotpress” should check for account | WordPress.org](https://wordpress.org/support/topic/warning-for-major-updates-in-this-version-of-zotpress-should-check-for-account/)
	- No mention of issue in zotpress support forum
	- Possibly try a more incremental upgrade, to 7.0?
	- If that fails, could try to manually back up and then import zotpress options through sql? (Or post an issue)

>  Changing theme --> zotpress settings get wiped?
	- Kendra Preston Leonard --- help her upgrade her theme?

**Comment by mikethicke** [comment]
Account info is stored in the wp_<blog_id>_zotpress table. Confirm that updating zotpress clears this table. It clears the other tables as well, though these don't seem critical.

Zotpress tables: 
- wp_1001985_zotpress
- wp_1001985_zotpress_cache
- wp_1001985_zotpress_oauth
- wp_1001985_zotpress_zoteroItemImages

Based on table structures (below), we could safely restore all but the cache table, which has an extra row.

There are about 100 sites with zotpress installed.

Table structures:
wp_1001985_zotpress;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| id           | int(9)       | NO   | PRI | NULL    | auto_increment |
| account_type | varchar(10)  | NO   |     | NULL    |                |
| api_user_id  | varchar(10)  | NO   |     | NULL    |                |
| public_key   | varchar(28)  | YES  |     | NULL    |                |
| nickname     | varchar(200) | YES  |     | NULL    |                |
| version      | varchar(10)  | YES  |     | 5.1     |                |
+--------------+--------------+------+-----+---------+----------------+
6 rows in set (0.00 sec)

wp_1001985_zotpress_backup;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| id           | int(9)       | NO   | PRI | NULL    | auto_increment |
| account_type | varchar(10)  | NO   |     | NULL    |                |
| api_user_id  | varchar(10)  | NO   |     | NULL    |                |
| public_key   | varchar(28)  | YES  |     | NULL    |                |
| nickname     | varchar(200) | YES  |     | NULL    |                |
| version      | varchar(10)  | YES  |     | 5.1     |                |
+--------------+--------------+------+-----+---------+----------------+
6 rows in set (0.00 sec)

wp_1001985_zotpress_cache;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(9)       | NO   | UNI | NULL    | auto_increment |
| request_id  | varchar(200) | NO   | PRI | NULL    |                |
| api_user_id | varchar(50)  | YES  |     | NULL    |                |
| json        | blob         | YES  |     | NULL    |                |
| tags        | blob         | YES  |     | NULL    |                |
| headers     | mediumtext   | YES  |     | NULL    |                |
| libver      | int(9)       | YES  |     | NULL    |                |
| retrieved   | varchar(100) | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
8 rows in set (0.00 sec)

wp_1001985_zotpress_cache_backup;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(9)       | NO   | UNI | NULL    | auto_increment |
| request_id  | varchar(200) | NO   | PRI | NULL    |                |
| api_user_id | varchar(50)  | YES  |     | NULL    |                |
| json        | blob         | YES  |     | NULL    |                |
| headers     | mediumtext   | YES  |     | NULL    |                |
| libver      | int(9)       | YES  |     | NULL    |                |
| retrieved   | varchar(100) | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
7 rows in set (0.00 sec)

wp_1001985_zotpress_oauth;
+-------+----------+------+-----+---------+----------------+
| Field | Type     | Null | Key | Default | Extra          |
+-------+----------+------+-----+---------+----------------+
| id    | int(9)   | NO   | PRI | NULL    | auto_increment |
| cache | longtext | NO   |     | NULL    |                |
+-------+----------+------+-----+---------+----------------+
2 rows in set (0.00 sec)

describe wp_1001985_zotpress_oauth_backup;
+-------+----------+------+-----+---------+----------------+
| Field | Type     | Null | Key | Default | Extra          |
+-------+----------+------+-----+---------+----------------+
| id    | int(9)   | NO   | PRI | NULL    | auto_increment |
| cache | longtext | NO   |     | NULL    |                |
+-------+----------+------+-----+---------+----------------+
2 rows in set (0.00 sec)

wp_1001985_zotpress_zoteroItemImages;
+-------------+-------------+------+-----+---------+----------------+
| Field       | Type        | Null | Key | Default | Extra          |
+-------------+-------------+------+-----+---------+----------------+
| id          | int(9)      | NO   | UNI | NULL    | auto_increment |
| api_user_id | varchar(50) | NO   | PRI | NULL    |                |
| item_key    | varchar(50) | NO   | PRI | NULL    |                |
| image       | text        | YES  |     | NULL    |                |
+-------------+-------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)

describe wp_1001985_zotpress_zoteroItemImages_backup;
+-------------+-------------+------+-----+---------+----------------+
| Field       | Type        | Null | Key | Default | Extra          |
+-------------+-------------+------+-----+---------+----------------+
| id          | int(9)      | NO   | UNI | NULL    | auto_increment |
| api_user_id | varchar(50) | NO   | PRI |         |                |
| item_key    | varchar(50) | NO   | PRI |         |                |
| image       | text        | YES  |     | NULL    |                |
+-------------+-------------+------+-----+---------+----------------+

**Comment by mikethicke** [comment]
Zotpress has an option ```Zotpress_update_version``` that it compares against a global variable set in zotpress.php --- ```Zotpress_update_db_by_version```. If these don't match, then the zotpress install is run, which drops all database tables and recreates them.

This probably isn't the best way of doing things. It would be better to run dbDelta to update the table structure without dropping the tables. This would only be an issue if the format of the data itself changed, rather than adding fields or something. It might be worth making a pull request on the plugin to make a less destructive update process.

**Comment by bjr70** [comment]
This is fixed.
