### ISSUE TITLE
Email notifications generated by hc-dev have stray html

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#111]
- [X] Add to an appropriate Epic.

Tester (if different from issue creator):  Kathleen
Site: hcommons
Test Account: hctester30
Area (CORE, sites, profiles, groups, general): groups
If issue discovered on dev, does it also exist on prod? No

**Describe the issue**
Email notification of group activity has cut off <a> tag at the beginning.

**Comment by mikethicke** [comment]
Possibly an issue between buddypress-group-email-subscriptions and buddypress 4.4? Updating bpges to 4.0.0 might fix the issue.

**Comment by mikethicke** [comment]
This appears to be fixed after BP 9.0.0 update. Please retest.

![Screen Shot 2021-09-03 at 10.39.58 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/d4f850fc-52c7-44f3-b058-0fafc857f425)

**Comment by bjr70** [comment]
This appears fixed to me.
