### ISSUE TITLE
Email notifications generated by hc-dev come from noreply@hcommons-dev.org

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#112]
- [X] Add to an appropriate Epic.

Tester (if different from issue creator): Kathleen
Site: reply by email
Test Account: hctester30
Area (CORE, sites, profiles, groups, general): groups
If issue discovered on dev, does it also exist on prod? No

**Describe the issue**
Email notifications generated by hc-dev come from noreply@hcommons-dev.org; hence no reply even on messages that claim RBE availability

**Comment by mikethicke** [comment]
Possibly a dev vs. prod issue? Should consult with Eric if this issue persists.

**Comment by mikethicke** [comment]
This appears to be particular to discussions:

![Screen Shot 2021-09-07 at 9.22.34 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/7a227c3c-b825-48f5-b585-0b776d15e4e6)

![Screen Shot 2021-09-07 at 9.21.32 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/dd03d518-e523-4196-97cd-3e4fc7220987)

**Comment by mikethicke** [comment]
I believe I have a fix for this, though there are some further issues that might exist:

(1) Does replying by email actually work? It does not on dev. But neither does starting a topic on dev, and that does work on prod, so I think it might be a dev vs. prod issue.

(2) As discussed here: https://app.zenhub.com/workspaces/humanities-commons-61143609f268f000196abf18/issues/mesh-research/wordpress-sparkpost/4 we might want to investigate abandoning our fork of wordpress-sparkpost . One of our modifications no longer seems necessary and the other can be addressed through a filter.

**Comment by bjr70** [comment]
I have never successfully gotten reply-by-email to work.

**Comment by bjr70** [comment]
The emails come from hc@hcommons.org, but that email isn't monitored. Should it come from an address that's monitored?

**Comment by mikethicke** [comment]
A number of auto-generated emails come from hc@hcommons.org. It might be worth just having it forward to hello.
