### ISSUE TITLE
Create dev instance sync'd with hcdev for debugging

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#113]
In previous round of testing I ran into trouble replicating issues because my dev instance was not exactly the same as hcdev.

- [ ] Create a new EC2 instance based on hcdev with mysql database
- [ ] Document process of cloning hcdev

**Comment by rekmla** [comment]
Let's assign you one of the available instances. Chaucer should be available, I think Anne is done with it. It needs a data refresh and plugin updates.

**Comment by mikethicke** [comment]
Thanks Eric, that could work. I want to make sure that I'm on the same versions of everything as hcdev though, which is why I wanted to just clone the instance. Is there a list of the updates done so far that I can reference?

**Comment by ericknappe** [comment]
Chaucer HC plugins aligned with hcdev. Note that there are no enrollment flows for chaucer. Testing limited to existing users in registry.hcommons-dev.org

**Comment by ericknappe** [comment]
List of all updates in play on msudev and hcdev

`#WP UPDATES

wp --path=/srv/www/commons/current/web/wp core update --version=5.6.3
sudo -u www-data wp --path=/srv/www/commons/current/web/wp --url=hcommons.org core update-db
sudo -u www-data wp --path=/srv/www/commons/current/web/wp --url=ajs.hcommons.org core update-db
sudo -u www-data wp --path=/srv/www/commons/current/web/wp --url=arlisna.hcommons.org core update-db
sudo -u www-data wp --path=/srv/www/commons/current/web/wp --url=aseees.hcommons.org core update-db
sudo -u www-data wp --path=/srv/www/commons/current/web/wp --url=caa.hcommons.org core update-db
sudo -u www-data wp --path=/srv/www/commons/current/web/wp --url=mla.hcommons.org core update-db
sudo -u www-data wp --path=/srv/www/commons/current/web/wp --url=msu.hcommons.org core update-db
sudo -u www-data wp --path=/srv/www/commons/current/web/wp --url=sah.hcommons.org core update-db
sudo -u www-data wp --path=/srv/www/commons/current/web/wp --url=up.hcommons.org core update-db
sudo -u www-data wp --path=/srv/www/commons/current/web/wp core update-db --network

cd /srv/www/commons/current/web/app/plugins/
wp --path=/srv/www/commons/current/web/wp plugin update akismet --version=4.1.9
wp --path=/srv/www/commons/current/web/wp plugin update anthologize --version=0.8.0
wp --path=/srv/www/commons/current/web/wp plugin update autoptimize --version=2.8.3
wp --path=/srv/www/commons/current/web/wp plugin update avatar-privacy --version=2.5.2
wp --path=/srv/www/commons/current/web/wp plugin update classic-editor --version=1.6
wp --path=/srv/www/commons/current/web/wp plugin update edit-flow --version=0.9.6
wp --path=/srv/www/commons/current/web/wp plugin update elementor --version=3.2.2
wp --path=/srv/www/commons/current/web/wp plugin update essential-addons-for-elementor-lite --version=4.6.3
wp --path=/srv/www/commons/current/web/wp plugin update events-made-easy --version=2.1.119
wp --path=/srv/www/commons/current/web/wp plugin update events-manager --version=5.9.11.3
wp --path=/srv/www/commons/current/web/wp plugin update ewww-image-optimizer --version=6.1.3
wp --path=/srv/www/commons/current/web/wp plugin update feedwordpress --version=2020.0818
wp --path=/srv/www/commons/current/web/wp plugin update google-sitemap-generator --version=4.1.1
wp --path=/srv/www/commons/current/web/wp plugin update gutenberg --version=10.5.3
wp --path=/srv/www/commons/current/web/wp plugin update issuem --version=2.8.4
wp --path=/srv/www/commons/current/web/wp plugin update knight-lab-timelinejs --version=3.8.17.0
wp --path=/srv/www/commons/current/web/wp plugin update mashsharer --version=3.7.9
wp --path=/srv/www/commons/current/web/wp plugin update newsletters-lite --version=4.6.19
wp --path=/srv/www/commons/current/web/wp plugin update ninja-forms --version=3.5.4
wp --path=/srv/www/commons/current/web/wp plugin update participants-database --version=1.9.6.9
wp --path=/srv/www/commons/current/web/wp plugin update password-protected --version=2.4
wp --path=/srv/www/commons/current/web/wp plugin update post-types-order --version=1.9.5.6
wp --path=/srv/www/commons/current/web/wp plugin update pressforward --version=5.2.3
wp --path=/srv/www/commons/current/web/wp plugin update printfriendly --version=4.1
wp --path=/srv/www/commons/current/web/wp plugin update public-post-preview --version=2.9.3
wp --path=/srv/www/commons/current/web/wp plugin update redirection --version=5.1.1
wp --path=/srv/www/commons/current/web/wp plugin update tainacan --version=0.17.4
wp --path=/srv/www/commons/current/web/wp plugin update tinymce-advanced --version=5.6.0
wp --path=/srv/www/commons/current/web/wp plugin update user-switching  --version=1.5.6
wp --path=/srv/www/commons/current/web/wp plugin update video-conferencing-with-zoom-api --version=3.8.1
wp --path=/srv/www/commons/current/web/wp plugin update wordpress-importer --version=0.7
wp --path=/srv/www/commons/current/web/wp plugin update formassembly-web-forms --version=2.0.4
wp --path=/srv/www/commons/current/web/wp plugin update wp-polls --version=2.75.6
wp --path=/srv/www/commons/current/web/wp plugin update wp-accessibility --version=1.7.7
wp --path=/srv/www/commons/current/web/wp plugin update wp-fail2ban --version=4.3.0.9
wp --path=/srv/www/commons/current/web/wp plugin update wpfront-notification-bar --version=1.9.1.04012
wp --path=/srv/www/commons/current/web/wp plugin update wp-google-maps --version=8.1.11
wp --path=/srv/www/commons/current/web/wp plugin update wp-to-twitter --version=3.5.2
wp --path=/srv/www/commons/current/web/wp plugin update zotpress --version=6.2.4

cd /srv/www/commons/current/web/app/themes/
wp --path=/srv/www/commons/current/web/wp theme update twentyten --version=3.3
wp --path=/srv/www/commons/current/web/wp theme update twentyeleven --version=3.7
wp --path=/srv/www/commons/current/web/wp theme update twentytwelve --version=3.3
wp --path=/srv/www/commons/current/web/wp theme update twentythirteen --version=3.3
wp --path=/srv/www/commons/current/web/wp theme update twentyfourteen --version=3.1
wp --path=/srv/www/commons/current/web/wp theme update twentyfifteen --version=2.9
wp --path=/srv/www/commons/current/web/wp theme update twentysixteen --version=2.4
wp --path=/srv/www/commons/current/web/wp theme update twentyseventeen --version=2.7
wp --path=/srv/www/commons/current/web/wp theme update twentynineteen --version=1.4
wp --path=/srv/www/commons/current/web/wp theme update twentytwenty --version=1.7
wp --path=/srv/www/commons/current/web/wp theme update twentytwentyone --version=1.3

wp --path=/srv/www/commons/current/web/wp theme update dispatch --version=4.9.13
wp --path=/srv/www/commons/current/web/wp theme update hitchcock --version=2.0.2
wp --path=/srv/www/commons/current/web/wp theme update poseidon --version=2.2.3
wp --path=/srv/www/commons/current/web/wp theme update responsive --version=4.6.2
wp --path=/srv/www/commons/current/web/wp theme update reykjavik --version=2.0.4
wp --path=/srv/www/commons/current/web/wp theme update sparkling --version=2.4.8
wp --path=/srv/www/commons/current/web/wp theme update suits --version=1.5.2
wp --path=/srv/www/commons/current/web/wp theme update tainacan-interface --version=2.2.1
wp --path=/srv/www/commons/current/web/wp theme update vantage --version=1.17.2
wp --path=/srv/www/commons/current/web/wp theme update wp-bootstrap-starter --version=3.3.6


#BP UPDATES

cd /srv/www/commons/current/web/app/plugins/
wp --path=/srv/www/commons/current/web/wp plugin update commons-in-a-box --version=1.3.0
wp --path=/srv/www/commons/current/web/wp plugin update buddypress --version=9.0.0
wp --path=/srv/www/commons/current/web/wp plugin update buddypress-docs --version=2.1.6
wp --path=/srv/www/commons/current/web/wp plugin update external-group-blogs --version=1.6.2
wp --path=/srv/www/commons/current/web/wp plugin update event-organiser --version=3.10.7
wp --path=/srv/www/commons/current/web/wp plugin update buddypress-group-email-subscription --version=4.0.0
wp --path=/srv/www/commons/current/web/wp plugin update bbpress --version=2.6.6
wp --path=/srv/www/commons/current/web/wp plugin update invite-anyone --version=1.4.1
wp --path=/srv/www/commons/current/web/wp plugin update more-privacy-options --version=4.6
wp --path=/srv/www/commons/current/web/wp plugin update bp-groupblog --version=1.9.2
wp --path=/srv/www/commons/current/web/wp plugin update bp-mpo-activity-filter --version=1.3.2
wp --path=/srv/www/commons/current/web/wp plugin update gd-bbpress-attachments --version=4.2
wp --path=/srv/www/commons/current/web/wp plugin update buddypress-restrict-group-creation  --version=1.1.2
wp --path=/srv/www/commons/current/web/wp plugin update buddypress-sitewide-activity-widget --version=1.3.5

cd /srv/www/commons/current/web/app/plugins/
wp --path=/srv/www/commons/current/web/wp plugin install --force https://github.com/r-a-y/bp-reply-by-email/archive/refs/tags/1.0-RC10.zip

cd /srv/www/commons/current/web/app/plugins/
wp --path=/srv/www/commons/current/web/wp plugin install --force https://github.com/MESH-Research/bp-group-documents/archive/refs/heads/v1.12.3.zip
`

**Comment by mikethicke** [comment]
Thanks Eric, much appreciated!

**Comment by rekmla** [comment]
Note we should discuss chaucer:/home/ubuntu/dev-scripts/common/sync_db_and_files_from_hcommons.bash

**Comment by mikethicke** [comment]
Sounds good, thanks.
