### ISSUE TITLE
Replace vimeo CC video with youtube version

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#114]

**Comment by mikethicke** [comment]
> 	
bonnie
11:35 AM
@adonlon @kfitz there's a broken video on the CORE search page (right side under the facets) that looks like it was on vimeo. Do we know what that video is? Does it still exist? https://hcommons.org/deposits/ Should it be removed or replaced with something? 

Today
	
adonlon
9:55 AM
I think it was the creative commons license video. Looks like it's also linked here: https://hcommons.org/core/faq/

	
bonnie
9:56 AM
Thank you!

9:57 AM


@mikethicke can we replace it with this video? https://www.youtube.com/watch?v=dPZTh2NKTm4


YouTube - What is Creative Commons?

**Comment by kfitz** [comment]
Replaced video URL in Video widget in Deposits Directory Sidebar.
