### ISSUE TITLE
Spam messages in activity feed linking to malware

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#120]
- [x] Add to an appropriate Epic

Date first reported: 9/8/2021
Date requested for completion:
Site: Humanities Commons
Area (CORE, profiles, sites, groups, account ): profile

**Description**
Spammers signing up and posting links to malware in the activity feed at other users: 

@angelabaggetta Hello,
We recom­mend testing our new project – http://1705555.com/hcommons/11230

We hope you enjoy it!
———————————————-
Sorry for interrupting.
From SW. Resource support!

The link they are spamming directs to https://apk-storage.club/away.php which redirected to https://captchaverifier.top/robot4/index.html?c=3f50d264-0a65-4299-a064-8f990d5213f0&a=l11222 -- malware https://www.computips.org/remove-captchaverifier-top/

Emails involved so far: 
iansmith8.11.8.017@gmail.com
thomascoop.m.r151985@gmail.com
dylangil.l6.56.6.9.30@gmail.com
benjaminhern.mr.2.11990@gmail.com
andrewsch.m.r0219.90@gmail.com

Are these users coming from the same IP? Can we ban by IP or filter out messages with that structure? 

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**

**Comment by mikethicke** [comment]
Added the following to hc-custom for testing on dev:

```
/**
 * Mark messages as spam that Akismet might have missed but we know are spam.
 *
 * Note: this is a temporary fix, and we probably want a more robust way of doing this.
 *
 * @author Mike Thicke
 *
 * @param BP_Activity_Activity $activity The activity item to check.
 */
function hc_custom_check_activity( $activity ) {
	if ( empty( $activity->content ) ) {
		return;
	}

	$blocked_patterns = [
		'/We recom­mend testing our new project –/',
	];

	foreach ( $blocked_patterns as $pattern ) {
		if ( preg_match( $pattern, $activity->content ) ) {
			bp_activity_mark_as_spam( $activity );
		}
	}
}
add_action( 'bp_activity_before_save', 'hc_custom_check_activity', 10, 1 );
```

**Comment by bjr70** [comment]
Another email frankbarmr30.1.9.9.5@gmail.com

**Comment by bjr70** [comment]
Is it preventing an account from posting further if they post that message? It looks like both hctester90 and 100 are prevented from posting activity updates after they post that message. Something odd is happening otherwise.

**Comment by bjr70** [comment]
This is interesting. One of the first was iansmith8.11.8.017@gmail.com, I just banned iansmith.8.11.8.0.1.7@gmail.com. Looks like iterations?

**Comment by mikethicke** [comment]
Since marking the activity as spam marks the user as a spammer, want to be really sure that it actually is spam.

- [ ] Check for a link in the activity

**Comment by bjr70** [comment]
new email gggiaccio1994@kasbodecon.tk

**Comment by mikethicke** [comment]
Should we close this?

**Comment by bjr70** [comment]
Filter appears to be working and no reports of any issues. Closing.
