### ISSUE TITLE
SAH Flat File for upload

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#127]
- [ ] Add to an appropriate Epic

Date first reported: 9/10/2021
Date requested for completion: 9/14/2021
Site: SAH Commons
Area (CORE, profiles, sites, groups, account ): member list

**Description**
New user list for upload: [https://app.zenhub.com/files/19561322/2418cffe-2757-4c2a-b1f8-6481972debfe/download](https://app.zenhub.com/files/19561322/2418cffe-2757-4c2a-b1f8-6481972debfe/download)

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**

**Comment by mikethicke** [comment]
New file uploaded.
