### ISSUE TITLE
Critical error when going to settings on up.hcommons-dev.org

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#128]
- [x] Add to an appropriate Epic.

Tester (if different from issue creator): Bonnie
Site: up.hcommons-dev.org
URL: https://up.hcommons-dev.org/members/hctester40/settings/
Test Account: hctester40 (Ferdinand Test)
Area (CORE, sites, profiles, groups, general): settings
If issue discovered on dev, does it also exist on prod? I can't enroll Ferdinand Test with UP on prod, but I believe this is a development issue. 

**Describe the issue**
![layoutissuessettingsedge.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/e9640b16-1d5e-46f3-ac39-80a2c983aeb4)

The entire screen is wonky and it's giving the error "There has been a critical error on this website."

This is not happening on hcommons-dev.org or mla.hcommons-dev.org, only up.hcommons-dev.org. Appears to be local to UP. 

**To Reproduce**
1. Log in as Ferdinand Test
2. Click on Settings
3. See error

**Expected behavior**

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
Should be fixed.

See: https://github.com/MESH-Research/boss-child/pull/101

**Comment by bjr70** [comment]
Fixed!

**Comment by bjr70** [comment]
Fixed.
