### ISSUE TITLE
Email failing -- no email is sent from hc-dev

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#132]
- [ ] Add to an appropriate Epic.

Tester (if different from issue creator): 
Site: hc-dev
URL: hcommons-dev.org
Test Account: hctester40
Area (CORE, sites, profiles, groups, general): email
If issue discovered on dev, does it also exist on prod? No, email is working

**Describe the issue**
No email is being sent from hc-dev. 

**To Reproduce**

**Expected behavior**

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
We had the wrong Sparkpost API key, perhaps an artifact of the syncing process? Should be working now.

**Comment by bjr70** [comment]
emails now working, separate issue created for daily digest failures.
