### ISSUE TITLE
Remove deposit by Jim Harries from CORE (again)

### ISSUE THREAD

**Issue by katknow** [MESH-Research/commons#134]
- [x] Add to an appropriate Epic

Date first reported: 9/15/2021
Date requested for completion:
Site: Humanities Commons
Area (CORE, profiles, sites, groups, account ): CORE

**Description**
User Jim Harries uploaded a book cover as an advertisement along with Amazon link so deposit needs to be removed from CORE. Deposit titled "How Western Anti-Racism Harms Africa and How we can do Better."

**Further details**
COmanage: https://registry.hcommons.org/registry/co_people/canvas/124202 
WP: https://hcommons.org/members/jimoharries/ 
Deposit: https://hcommons.org/deposits/item/hc:41429/

**Comment by rekmla** [comment]
Removed.
