### ISSUE TITLE
Daily Digest emails not working

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#135]
- [x] Add to an appropriate Epic.

Tester (if different from issue creator): hctester40
Site: hcommons-dev
URL: https://hcommons-dev.org/groups/shelley-appreciation-group/
Test Account: hctester40
Area (CORE, sites, profiles, groups, general): groups
If issue discovered on dev, does it also exist on prod? no

**Describe the issue**
As user bonnie I created a new discussion and uploaded a file on 9/15 and hctester40 was set to receive a daily digest and did not. I changed hctester40 to all email for the group, created another discussion topic and uploaded a file and received email to hctester40's gmail account.

**To Reproduce**
1. Set user's email for a group to daily digest
2. Create a discussion post and upload a file
3. Check for email the next day
4. Change user's email for a group to all email
5. repeat step 2
6. Email received

**Expected behavior**
A daily digest of all activity on the group should be emailed to the user. 

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser both chrome and firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
Since this is part of BPGES, I'm going to hold off on tackling this until that can be upgraded.
