### ISSUE TITLE
Name entered during registration does not appear on profile. 

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#138]
- [x] Add to an appropriate Epic.

Tester (if different from issue creator): 
Site: MLA Commons profile
URL: https://mla.hcommons-dev.org/members/hctester10/
Test Account: hctester10
Area (CORE, sites, profiles, groups, general): profile
If issue discovered on dev, does it also exist on prod? Not sure 

**Describe the issue**
The tester name I entered during registration does not appear on the profile. The name does appear in the upper right, beside the avatar in the header. The title and affiliation from the MLA database correctly populated on the profile. 

Perhaps relatedly, 

- the MLA badge is missing (though the tester has access to join MLA Commons groups)
- the account doesn't seem to appear in the member directory. 
- MLA doesnt appear under "Current memberships" on settings.
- The first few times I clicked on "Settings" on the dropdown menu below the avatar I was redirected to the hc (dev) homepage, ie a page not found. When I clicked on "General" beside "settings" the page loaded. The page loads correctly on prod. And after getting the page to load, I can't replicate this. 

**To Reproduce**
1. Register a tester with MLA membership. 
2. Check the profile's name field.
3. Check for MLA badge.
4. Check Settings / Current memberships
5. Check /members

**Expected behavior**
The name entered during registration should appear on the profile. 

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
The name (Barty Test) does appear in WP Admin, so it's not an enrollment issue.

Name is blank when you edit profile. When profile is edited, name in profile appears, and is also changed in WP Admin.

**Comment by mikethicke** [comment]
Ready for testing.

See: https://github.com/MESH-Research/humanities-commons/pull/49

**Comment by adonlon** [comment]
Name was filled correctly on profile upon registration. This fixed worked! Thanks, @mikethicke .

I'll create another issue for the other issues remaining. (And I realized that not appearing in /members is not a problem--it doesn't show yourself in the list of members. Logged in with a different account i see the tester in the member directory.)

**Comment by bjr70** [comment]
Member type is blank on enrollment. No "HC."
