### ISSUE TITLE
Contact AJS and CAA Commons users to notify of commons retirements and HC membership

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#142]
- [ ] Add to an appropriate Epic

Date first reported:  9/20/2021
Date requested for completion: 12/31/2021
Site: AJS and CAA Commons
Area (CORE, profiles, sites, groups, account ): users/profiles

**Description**
Contact users to let them know they can use Humanities Commons (or another one they belong to) to continue to maintain their digital presence

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**

**Comment by bjr70** [comment]
[Sample template here](https://viewstripo.email/d41a736f-3b30-45f9-ba6a-ea6b3460b26c1632331947503)

**Comment by mikethicke** [comment]
CAA and AJS emails sent.

**Comment by mikethicke** [comment]
Ended up taking a bit longer than expected as I had to generate society-specific recipient lists.
