### ISSUE TITLE
Archive AJS and CAA Commons and remove from the internet

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#143]
- [ ] Add to an appropriate Epic

Date first reported: 9/20/2021
Date requested for completion: 12/31/2021
Site: AJS and CAA Commons
Area (CORE, profiles, sites, groups, account ): entire sites

**Description**
Archive and remove both commonses from the internet (we could restore them if the orgs decide to come back

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**

**Comment by mikethicke** [comment]
## In WordPress

- CAA and AJS sites archived
- Image directories archived and deleted
- Sites deleted
- Nginx redirects created
- Styles removed from Boss Child theme https://github.com/MESH-Research/boss-child/commit/475599768f4ee1d89979a154f2f66f3d73bafbd9
- Society configurations removed from Humanities Commons plugin https://github.com/MESH-Research/humanities-commons/commit/c8d6b8dd9d04d15e0648ef220076f7474a66a1f4
- WP-to-Twitter configurations removed: https://github.com/MESH-Research/hc-custom/commit/935b9aafa3463ce396c7a0f415413f6e675bb329
- Badges and styles removed

# In COmanage

- Enrollment flows deleted
- Groups deleted
- COUs deleted
- Organizational Identity Sources deleted

COUs not deleted as they cannot be removed if there are members still in them.
