### ISSUE TITLE
Clicking anywhere on a site using 15zine (e.g. Ask UP) on dev loads mostly empty page.

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#147]
- [ x] Add to an appropriate Epic.

Tester (if different from issue creator): 
Site: Ask UP and likely all using 15zine theme: https://president.mla.hcommons-dev.org/; https://colearning.hcommons-dev.org/; https://assemblage.hcommons-dev.org/; etc.)
URL: https://ask.up.hcommons-dev.org/
Test Account: logged out, adonlon, hctester10
Area (CORE, sites, profiles, groups, general): site
If issue discovered on dev, does it also exist on prod? no

**Describe the issue**
Clicking anywhere on Ask UP on dev loads a mostly empty page, bank except an X in the upper right corner (<html class="swipebox-html swipebox-no-touch" lang="en-US">). Click on a link, text box, anywhere on the page, WP toolbar--and this page will load. Seems like a theme issue; the admin dashboard for the site works. 

-----previous description---
When I click on "log in" from the site, I get a white page, blank except for an x in the upper right. 

I checked another UP subsite on dev and it loaded the login page, so it doesn't seem to be a network wide problem.

When I visit the site logged in as a site admin, I am not able to navigate to the admin dashboard from the WP toolbar at the top. The same blank page with X in the upper right loads. 

Perhaps something with the theme? I also noticed that there is a search bar at the top of the site on prod that is missing on dev. 

**To Reproduce**
1. Go to https://ask.up.hcommons-dev.org/
2. When logged out, click on "log in" in the upper left. 
2b. When logged in, click "My Sites" or "Widgets" (if a site admin).
2c. Click anywhere on the page, a link, a text entry box, or anywhere on the page.
3. See blank page with x in upper right. 

**Expected behavior**
I expect the login page to load, the admin dashboard to load, the linked page to load, or nothing (in the case of clicking unlinked parts of the page).

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adonlon** [comment]
It seems to be clicking on anything in the top WP toolbar that results in the white page, blank except for the X in upper right. If visiting the site logged in as a site admin, for instance, cannot visit the admin dashboard or "my sites" from the toolbar. I'll update the issue.

**Comment by adonlon** [comment]
Sorry for the constant updating. It seems to be clicking anywhere on the Ask UP site on dev that causes that screen to load. There are no console errors when it comes up. 

<html class="swipebox-html swipebox-no-touch" lang="en-US"><head>

**Comment by adonlon** [comment]
This seems to affect all sites using the 15zine theme. The theme update likely needs a wider review. There are other differences between sites on dev and prod, e.g. layout of https://colearning.hcommons-dev.org/, missing search bar on Ask UP. Currently hard to explore because of the lack of clicking!

**Comment by mikethicke** [comment]
Looks like the culprit is the swipebox jQuery plugin that the theme is using. Has an event listener for document.click. Removing the listener stops the behavior. Should see if there is an update for the theme that updates that plugin.

**Comment by mikethicke** [comment]
15zine is a themeforest theme. Should update to latest version if possible.

As a stop-gap, I replaced /srv/www/commons/current/web/app/themes/15zine/assets/js/swipebox.min.js with the latest version from https://github.com/brutaldesign/swipebox/blob/master/src/js/jquery.swipebox.min.js and that seems to solve the issue. If we don't have a theme update when we push updates to production, we should make the same swap there.
