### ISSUE TITLE
MLA Publications Committee trouble uploading docs

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#149]
Site (Humanities Commons, MLA Commons, UP Commons, etc.): MLA Commons
URL: https://mla.hcommons.org/groups/publications-committee/
User Account: James Hatch
Area (CORE, sites, profiles, groups, general): groups

**Describe the bug**
Members of the publications committee have a longstanding issue with creating and uploading docs, especially docs with attachments. This appears to be especially a problem for James Hatch, but also Jamie.

Additionally, James has a problem where he cannot view the documents he uploaded in their proper locations. Sometimes can see in activity feed.

I have been able to reproduce the visibility issue but not the upload issue.

**Comment by bjr70** [comment]
Can't reproduce on dev

**Comment by mikethicke** [comment]
Addressed an issue where if you clicked 'Add Files' too quickly, a permissions check will fail, causing uploads to fail in turn:

- [commons-149-disable-add-files-until-ready](https://github.com/MESH-Research/hc-custom/commit/33c9a5a5052a9ac38211b93bedddb05a80795f6e)
- [commons-149-dont-disable-add-files-for-existing-docs](https://github.com/MESH-Research/hc-custom/commit/0e8203c753b3d1d0c6914cf3468c4f27e2651983)

I haven't been able to create any other failure states either on Dev or Prod, including when using the affected accounts.

I have inserted some logging statements into the attachments upload script (goes to /srv/www/commons/logs/hcommons_error.log) that trigger if James or Jamie tries to upload an attachment. I will need to see some failures in the logs to proceed.

**Comment by mikethicke** [comment]
After this fix James reported uploads were working for him. The delays can be quite significant so this was possibly the issue.
