### ISSUE TITLE
Remove users from society groups when no longer members of that society

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#152]
Users are automatically added to groups if they are members on Comanage and members of the corresponding society by hc-simplesaml.php::hcommons_set_user_member_types. However, users are not removed from groups if they are not members of the society.

There is a TODO for this in the function:
```
//If site is a society we are mapping groups for and the user is member of the society, map any groups from comanage to wp.
	//TODO add logic to remove groups the user is no longer a member of
	if ( in_array( Humanities_Commons::$society_id, array( 'ajs', 'arlisna', 'aseees', 'caa', 'mla', 'msu', 'sah', 'up' ) ) &&
		in_array( Humanities_Commons::$society_id, $memberships['societies'] ) ) {
		if ( isset( $memberships['groups'][Humanities_Commons::$society_id] ) ) {
			foreach( $memberships['groups'][Humanities_Commons::$society_id] as $group_name ) {
				//$group_id = $this->hcommons_lookup_society_group_id( Humanities_Commons::$society_id, $group_name );
				$group_id = Humanities_Commons::hcommons_lookup_society_group_id( Humanities_Commons::$society_id, $group_name );
				if ( ! groups_is_user_member( $user_id, $group_id ) ) {
					$success = groups_join_group( $group_id, $user_id );
					hcommons_write_error_log( 'info', '****ADD_GROUP_MEMBERSHIP***-' . $group_id . '-' . $user_id );
				}
			}
		}
	}
```

Implement that removal.

Related to MESH-Research/commons#144

**Comment by mikethicke** [comment]
Users should now be removed from society groups if they are not a member of that society upon login.

**Comment by mikethicke** [comment]
@bjr70 @adonlon - This might be a hard one to test since users are not supposed to be able to join society groups unless they are members. We might have to think about a way to add users to groups for testing purposes.

**Comment by adonlon** [comment]
Another case would be when society or institutional membership expires—though that may also be a bit involved to test, we'd have to join some testers to society groups and then expire the memberships. 

Barty Test has only HC and MLA Commons group memberships now.

**Comment by bjr70** [comment]
This testing is being completed with issue [#commons344](https://app.zenhub.com/workspaces/humanities-commons-61143609f268f000196abf18/issues/mesh-research/commons/344). Will close together.
