### ISSUE TITLE
Post images not displaying on Connected Academics homepage

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#153]
Site (Humanities Commons, MLA Commons, UP Commons, etc.): MLA Commons -- Connected Academics
URL: https://connect.mla.hcommons.org/. 
User Account: logged out, adonlon
Area (CORE, sites, profiles, groups, general): sites

**Describe the bug**
All but one of the post images on the Connected Academics site are not loading on the homepage.

e.g.
```<figure class="entry-image">
    	<a href="https://connect.mla.hcommons.org/2019-boot-camp-fellows/">
			<img src="https://connect.mla.hcommons.org/files/2018/11/5c6YvbNy_400x400-330x330.jpg" class="attachment-masonry-size size-masonry-size wp-post-image" alt="MLA 2019 logo" loading="lazy" itemprop="image" srcset="https://connect.mla.hcommons.org/files/2018/11/5c6YvbNy_400x400-330x330.jpg 330w, https://connect.mla.hcommons.org/files/2018/11/5c6YvbNy_400x400-150x150.jpg 150w, https://connect.mla.hcommons.org/files/2018/11/5c6YvbNy_400x400-300x300.jpg 300w, https://connect.mla.hcommons.org/files/2018/11/5c6YvbNy_400x400.jpg 400w" sizes="(max-width: 330px) 100vw, 330px" width="330" height="330">    	</a>
            </figure>
```

**To Reproduce**
1. Go to https://connect.mla.hcommons.org/
2. Look at recent posts displayed on homepage.
3. See blank spaces where images should be.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome and Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
The <figure> element has opacity 0 for screen widths over 751px. Not sure what the intended effect is.

**Comment by mikethicke** [comment]
This site is using the SimpleMag theme. We have version 3.0.4 . The current version is [5.5](https://themeforest.net/item/simplemag-magazine-theme-for-creative-stuff/4923427). If we're keeping this theme I would suggest upgrading to the latest version.

**Comment by mikethicke** [comment]
We're looking into paying to update this and other themeforest themes.

**Comment by mikethicke** [comment]
The latest version of simplemag does fix this issue. See: https://connect.mla.msucommons-dev.org/

However, sites with this theme will require manual updating as the layout editor works differently in the newest version and it doesn't cleanly transfer layout settings from the older version. There are 20 sites that use this theme.
