### ISSUE TITLE
Theme options not retained on dev (15zine / President blog on MLA Commons)

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#154]
- [x ] Add to an appropriate Epic.

Tester (if different from issue creator): 
Site: President blog on MLA Commons
URL: https://president.mla.hcommons-dev.org/
Test Account: adonlon
Area (CORE, sites, profiles, groups, general): sites
If issue discovered on dev, does it also exist on prod? No

**Describe the issue**
Theme options from prod have not been retained on dev. 
For example, on prod, the post options specify that author name is not displayed for posts. https://president.mla.hcommons.org/wp-admin/themes.php?page=ot-theme-options
On dev, "show author" is on. (https://president.mla.hcommons-dev.org/wp/wp-admin/themes.php?page=ot-theme-options)

**To Reproduce**
1. Go to 'president.mla.hcommons-dev.org' and https://president.mla.hcommons-dev.org/wp/wp-admin/themes.php?page=ot-theme-options (under meta elements)
2. See post author displayed on homepage / theme option for show author is on.
3. Compare with homepage and theme options on prod. 

**Expected behavior**

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
I suspect this is just a syncing issue, but we should check to make sure when we update prod.

**Comment by mikethicke** [comment]
I think MESH-Research/commons#151 is the same issue.

**Comment by mikethicke** [comment]
Redundant with #151 and seems to be an issue with syncing site options.
