### ISSUE TITLE
Ninja Form on MLA Commons Bibliography - error with required fields and conditional logic

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#156]
Site (Humanities Commons, MLA Commons, UP Commons, etc.): MLA Commons - Bibliography site
URL: https://mlabib.mla.hcommons.org/mla-bibliography-submission-form/
User Account: 
Area (CORE, sites, profiles, groups, general): sites / plugin

**Describe the bug**
Ninja Forms conditional logic is not handling required fields. 

**To Reproduce**
1. Go to https://mlabib.mla.hcommons.org/mla-bibliography-submission-form/
2. Select Scholarly Web site
3. Fill out required field (email) 
4. Hit Submit.
5. See error: Please correct errors before submitting this form. [But no errors are visible.]

**Expected behavior**
The form should allow you to submit it and/or show you what errors need to be corrected in order for it to be submitted. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
In this version of Ninja Forms at least (not sure how it worked previously), required fields are required regardless of whether they are displayed. If a required field is hidden by a particular publication type, you can't submit the form. The fix here is either to make separate forms for each publication type or to only make required fields that are visible for all publication types.

**Comment by bjr70** [comment]
@adonlon did you need anything from me on this?

**Comment by mikethicke** [comment]
Could make a feature request to Ninja Forms for conditional required fields.

**Comment by bjr70** [comment]
This is still happening on dev. Everything else seems to work OK.

**Comment by bjr70** [comment]
Form still throwing error.

**Comment by mikethicke** [comment]
Do we pay for Ninja Forms? I can put in a feature request, but IMO Ninja Forms is working correctly in this case and this isn't really our problem.

**Comment by bjr70** [comment]
I don't actually know. @ericknappe are we using the paid version?
