### ISSUE TITLE
Retire AJS and CAA in coManage

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#160]
- [ ] Add to an appropriate Epic

Date first reported: 10/6/2021
Date requested for completion: 12/31/2021
Site: AJS Commons, CAA Commons
Area (CORE, profiles, sites, groups, account ): All

**Description**
Retired AJS and CAA in comanage

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**

**Comment by mikethicke** [comment]
DEV:

- [x] Delete all CAA & AJS groups
- [x] Delete all CAA & AJS Organizational Identity Sources
- [x] Delete CAA & AJS Pipelines
- [x] Delete CAA & AJS Themes

PROD:

- [x] Delete all CAA & AJS groups
- [x] Delete all CAA & AJS Organizational Identity Sources
- [x] Delete CAA & AJS Pipelines
- [x] Delete CAA & AJS Themes

**Comment by mikethicke** [comment]
Cannot delete CAA or AJS COUs as they have CO records attached (?) to them. Not sure how / whether to get rid of these.
