### ISSUE TITLE
New login method linking broken in MSU Commons

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#165]
Site (Humanities Commons, MLA Commons, UP Commons, etc.): 
URL: https://msu.hcommons.org/
User Account: bonnie (all users affected)
Area (CORE, sites, profiles, groups, general): settings/general/link login method

**Describe the bug**
The link to add a new login method is missing and replaced with "Linking other log-in methods is currently unavailable." Multiple users including Kelly, Kristen, and I have tried it. Found by Rocío Quispe-Agnoli - [hcommons profile](https://hcommons.org/members/quispeag/).

**To Reproduce**
1. Go to settings/general on commons.msu.edu or msu.hcommons.org
2. Under link another account method the link is missing. 

**Expected behavior**
A link should appear allowing a user to add a login method.

**Screenshots**
![linkaccountmethodbroken.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/27caf946-eebc-4edb-8711-0a9f4a715cda)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows, OSX
 - Browser [e.g. chrome, safari] chrome, firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
This was disabled on production in the .env file. I re-enabled it and successfully linked my account to Twitter from commons.msu.edu. Can someone retest?

**Comment by bjr70** [comment]
Fixed!
