### ISSUE TITLE
Google Analytics+ discontinued. Beehive as replacement?

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#170]
- [x] Add to an appropriate Epic

Date first reported: 10/18/2021
Date requested for completion: 10/31/2021
Site: https://scholarlytales.hcommons.org/
Area (CORE, profiles, sites, groups, account ): sites

**Description**
User reported that Google Analytics is not returning data for their site - https://scholarlytales.hcommons.org/.

From discussion with Mike on Mattermost: "so we have both beehive and Google Analytics + on dev. Beehive is up-to-date, Google Analytics + hasn't been updated since 2014. They are from the same developer, and it looks like beehive replaced Google Analytics+. However, I'm not sure Beehive is actually activated anywhere, while Google Analytics+ still is. On production, Beehive isn't installed."

Need to determine whether Beehive is the tool moving forward and fix Google Analytics for users.

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**

**Comment by mikethicke** [comment]
Installed beehive on dev and deactivated Google Analyics +. Beehive looks good.

**Comment by bjr70** [comment]
[email notification template](https://app.zenhub.com/files/19561322/c4356954-7611-484b-86f4-fffc3596b748/download)

**Comment by bjr70** [comment]
[updated template](https://app.zenhub.com/files/19561322/c776ce00-b426-4ccd-b393-c10b96f0aa1e/download)

**Comment by mikethicke** [comment]
Google Analytics+ has been deactivated on all networks except MLA.
