### ISSUE TITLE
Remove Scholarpress Coins plugin from the site

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#177]
- [x] Add to an appropriate Epic

Date first reported: 
Date requested for completion: 12/31/2021
Site: All commonses
Area (CORE, profiles, sites, groups, account ): Sites

**Description**
https://wordpress.org/plugins/scholarpress-coins/

Scholarpress Coins was removed from the WordPress platform in 2019 for guideline violations. It has in the past caused issues with sites. We should note anyone still using it and remove it from the platform.

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**

**Comment by mikethicke** [comment]
Removing the plugin does affect the metadata available to Zotero.

Before removal:
![Screen Shot 2021-12-02 at 11.28.55 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/3e2b4921-a49e-40a5-9eb5-a4117e7b1933)

After removal:
![Screen Shot 2021-12-02 at 11.32.12 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/4f34e265-6ee2-4fda-a484-4c4e66d587f6)

Hold off on removing this for now until a replacement can be found / written.

**Comment by bjr70** [comment]
Closing. See issue: https://github.com/MESH-Research/commons/issues/631
