### ISSUE TITLE
pdfjs-viewer not displaying PDFs

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#178]
Site (Humanities Commons, MLA Commons, UP Commons, etc.):  MLA Commons / Bookish
URL: https://scholcomm.mla.hcommons.org/
User Account: 
Area (CORE, sites, profiles, groups, general): embedded PDFs

**Describe the bug**
The PDF embedder is not displaying the PDFs. e.g. https://scholcomm.mla.hcommons.org/mla-books/approaches-to-teaching-bechdels-fun-home

All of the posts that use that PDF embedder on the site can be accessed here: https://scholcomm.mla.hcommons.org/category/mla-books

On firefox it gives me this error 

> Firefox Can’t Open This Page .  To protect your security, hcommons.org will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window. On Safari, it is just blank. If I open in a new window in firefox as prompted I get An error occurred while loading the PDF. PDF.js v2.2.145 (build: 8bbae798)
> Message: NetworkError when attempting to fetch resource.

The shortcode on the post was `[pdfjs-viewer url="https%3A%2F%2Fscholcomm.mla.hcommons.org%2Ffiles%2F2020%2F03%2Fatt_bechdel_materials.pdf.pdf" viewer_width=100% viewer_height=1360px fullscreen=true download=true print=true]` .  I replaced the URL with this one `[https://scholcomm.mla.hcommons.org/files/2020/03/att_bechdel_materials.pdf.pdf]` but it didn't make a difference 

**To Reproduce**
1. https://scholcomm.mla.hcommons.org/mla-books/approaches-to-teaching-bechdels-fun-home

**Expected behavior**
Expect to view PDF.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
It looks like the underlying issue is that the PDF is being prevented from loading by cross origin scripting policies.

**Comment by mikethicke** [comment]
Going to remove plugin, replace with links.

**Comment by mikethicke** [comment]
Replaced pdfjs shortcodes with links in production, for all networks except MLA.

[https://app.zenhub.com/files/19561322/179f4768-5015-4bf3-b7bd-519aef181d84/download](https://app.zenhub.com/files/19561322/179f4768-5015-4bf3-b7bd-519aef181d84/download)

**Comment by mikethicke** [comment]
PDFJS has been mass deactivated on all networks except MLA, and activation has been prevented on all networks including MLA.
