### ISSUE TITLE
Update text on Create a Site page

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#180]
- [ ] Add to an appropriate Epic

Date first reported: 10/27/2021
Date requested for completion: 12/3/2021
Site: All commonses
Area (CORE, profiles, sites, groups, account ): Sites

**Description**
The text on the Create a Site page is confusing some users. The example I'm attaching is for HC, but similar changes should be made to all Commonses while preserving localizations. This feedback came from Sharon Leon, who is currently teaching courses on MSU. See the attached zipped html file. 

[HTML file](https://app.zenhub.com/files/19561322/312e1e3f-d6d3-44c7-813c-097049a06470/download)

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**

**Comment by mikethicke** [comment]
This took longer than expected as the code for the Create a Site page was spread over multiple functions and plugins.

I consolidated the code into hc-custom::buddypress-functions.php::hc_custom_bp_blogs_signup_blog() and remove the javascript in boss-child that had been used to override the text in the privacy options checkboxes. This code should no longer be necessary as the More Privacy Options function that created these fields no longer fires and they are created with the correct text by hc_custom_signup_blogform(). This change also affects the privacy options when creating a group site.

- [hc-custom](https://github.com/MESH-Research/hc-custom/commit/6b41f7d638a534b22ca4f5659e39318c1e2ec450)
- [boss-child](https://github.com/MESH-Research/boss-child)
