### ISSUE TITLE
Enrollment with HCID failed for hctester100

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#182]
- [ ] Add to an appropriate Epic.

Tester (if different from issue creator): 
Site: hcommons-dev.org
URL: https://registry.hcommons-dev.org/registry/co_people/canvas/127312
Test Account: hctester100
Area (CORE, sites, profiles, groups, general): enrollment
If issue discovered on dev, does it also exist on prod? No

**Describe the issue**
Tried to enroll hctester100 in HC with an HCID. Got an error on creating a username/password that the identifier was invalid. User ended up in confirmed status. 

https://registry.hcommons-dev.org/registry/co_people/canvas/127312

Could not copy the error because it flashed at the top of the screen and disappeared. It then refreshed and gave me "An Internal Error Has Occurred." 

Username was not created, had to search for user by email. 

**To Reproduce**

**Expected behavior**

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
When I try to enroll Rosie I get: Error provisioning account to LDAP at the 'Choose Your Username and Password for the Humanities Commons Login Server' step. I also get:

>Your username (this will be public) must only contain letters and numbers.
>Your password must be at least 10 characters long and include at least one number, lowercase letter, and uppercase letter.

But I am using the values from our test users spreadsheet which satisfy those requirments.

**Comment by mikethicke** [comment]
Registering hctester70, I get all the way to logging in with hcid, and then get an error message something like:

Invalid Field: identifier_status

In COmanage, they are stuck in confirmed, with no uid: https://registry.hcommons-dev.org/registry/co_people/canvas/127340

hctester70 is in SAH

**Comment by bjr70** [comment]
This is fixed. Closing.
