### ISSUE TITLE
Update Production WordPress instance

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#184]
Update prod-wordpress to match WordPress core, plugins, themes currently on dev-wordpress.

Preparation
- [x] Determine time for update
- [x] Write script to check repository statuses
- [x] Write script for updating plugins through WP-CLI
- [x] Create list of non wp.org plugins to update
- [x] Create main and production branches from current dev branches
- [x] Set block editor as default

Day of
- [x] Pull production branches to production (**not humcore**)
- [x] Update themes
- [x] Update plugins
- [x] Update WordPress to 5.8.1
- [x] Update site databases for each network
- [x] Update bbPress tables through admin
- [x] Test

**Comment by bjr70** [comment]
Thursday November 11 9am rollout

**Comment by mikethicke** [comment]
Script to check status of repos on WordPress instance: dev-scripts/commons/repo-status.py

**Comment by mikethicke** [comment]
Script to update plugins: ~/bp_plugin_update.bash

**Comment by mikethicke** [comment]
Themes to update:

- [ ] 15zine (Themeforest)
- [ ] digital-pedagogy (GitHub)
- [ ] simplemag (Themeforest) (**On Friday**)

**Comment by mikethicke** [comment]
To update site databases:

```
~/all_networks_wp.bash core update-db --network
```

**Comment by mikethicke** [comment]
Updated plugin update script to remove some updates that should have further testing, and add GitHub sources.
