### ISSUE TITLE
"Recommended for you" on the CORE page not working

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#189]
- [x] Add to an appropriate Epic.

Tester (if different from issue creator): 
Site: hcommons-dev.org
URL: https://hcommons-dev.org/core/
Test Account: Bonnie
Area (CORE, sites, profiles, groups, general): CORE 
If issue discovered on dev, does it also exist on prod? Works on prod

**Describe the issue**
This may be related to the CORE testing and migration, but the "recommended for you" section is showing "no results."

**To Reproduce**

**Expected behavior**

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
Should test post update to see if this was a sync issue.

**Comment by mikethicke** [comment]
This was caused primarily by changes to how indexing works in ElasticSearch and the architecture of the ElasticPress plugin.

See:
 - https://github.com/MESH-Research/elasticpress-buddypress/pull/10
 - https://github.com/MESH-Research/hc-suggestions/pull/4
 - https://github.com/MESH-Research/commons/commit/d1ecbb483307effd2efac67a5c5e76287b47c656
