### ISSUE TITLE
Digital Pedagogy broken on dev

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#199]
- [ ] Add to an appropriate Epic.

Tester (if different from issue creator): 
Site: Digital Pedagogy in the Humanities 
URL: digitalpedagogy.hcommons-dev.org
Test Account: 
Area (CORE, sites, profiles, groups, general): site
If issue discovered on dev, does it also exist on prod? No

**Describe the issue**
Pages not loading likely because of GraphQL upgrade. Eric let me know that there was a GraphQL upgrade on dev and recalled that Joseff warned that the next version of GraphQL would introduce breaking changes. That seems to be the case. Homepage loads and search page partially loads but other pages do not load. Collection bar is not present when logged in.

**To Reproduce**
1. Go to digitalpedagogy.hcommons-dev.org
2. Click on Keywords in horizontal menu
3. Page does not load. (Loading animation.) 
4. Click on About.
5. "Page Not Found" page loads.
6. Click on Search.
7. Tags and artifact types below search bar do not load. 

**Expected behavior**

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikethicke** [comment]
It looks like Digital Pedagogy is the only site using the GraphQL plugin. We'll hold off on updating the plugin this round. Is Joseff still working on the digital pedagogy theme, or would we have to update it ourselves?
