### ISSUE TITLE
Plugin Updates to Test and Deploy

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#202]
The following plugin updates were held back from deployment to production for further testing:

- [x] CommentPress
- [x] Ninja Forms
- [x] Wp-to-twitter
- [x] Wp-job-manager

Test to make sure they are functional and then deploy.

- [x] Deploy to production

**Comment by mikethicke** [comment]
- Need to check with AUP re: wp-job-manager
- Need to check with MLA (Anne) re: Ninja Forms
- One active site for CommentPress

**Comment by bjr70** [comment]
CommentPress looks OK and is ready to go.

**Comment by bjr70** [comment]
WP to Twitter looks OK and is ready to go.

**Comment by bjr70** [comment]
Other than the known issue with Ninja Forms and the conditional fields these look OK. Ready for move to production.
