### ISSUE TITLE
Notifications for discussion topic not sent out 

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#205]
Two recent topics in an MLA Commons forum group, https://mla.hcommons.org/groups/applied-linguistics/, did not generate notifications for users subscribed to "All email." (TBD whether daily/weekly  digests include the topic.) 

In case it's relevant: The two topics list "0 voices," which is not typical. (Usually a single post indicates 1 voice) e.g. https://mla.hcommons.org/groups/applied-linguistics/forum/topic/mahmoud-azaz-applied-linguistics-forum-executive-committee-candidate-statement-2/

**Comment by mikethicke** [comment]
I think this was a one-off issue related to non-members posting in society groups.
