### ISSUE TITLE
Update filters for ElasticSearch

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#212]
Update filters in ElasticSearch results.

- [x] There is a 'Landing Page' filter in the righthand menu of ElasticSearch results. Remove the filter.
- [x] Are the correct societies listed in filters? (Eg. should ARLISS be there?

**Comment by ericknappe** [comment]
Controlled by filters in hc-custom/includes/elasticpress-buddypress.php. In addition to Landing Page, we show AJS and CAA which are candidates for removal.

We are not showing the following that might be ready to be included, ARLIS/NA, MSU and SAH

`// Hide some networks & post types from search facets.
add_filter( 'ep_bp_show_network_facet_6', '__return_false' ); // UP.
add_filter( 'ep_bp_show_network_facet_7', '__return_false' ); // MSU.
add_filter( 'ep_bp_show_network_facet_8', '__return_false' ); // ARLIS.
add_filter( 'ep_bp_show_network_facet_10', '__return_false' ); // SAH.
add_filter( 'ep_bp_show_network_facet_11', '__return_false' ); // HUB.
add_filter( 'ep_bp_show_network_facet_12', '__return_false' ); // SOCSCI.
add_filter( 'ep_bp_show_network_facet_13', '__return_false' ); // STEM.
add_filter( 'ep_bp_show_post_type_facet_post', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_page', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_attachment', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_forum', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_bp_doc', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_event', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_bp_docs_folder', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_elementor_library', '__return_false' );
`

**Comment by mikethicke** [comment]
New settings:

```

/*
 * Networks ( Jan 2022 )
 * '1 : MLA Commons',
 * '2 : Humanities Commons',
 * '3 : AJS Commons',
 * '4 : ASEEES Commons',
 * '5 : CAA Commons',
 * '6 : UP Commons',
 * '7 : MSU Commons',
 * '8 : ARLIS/NA Commons',
 * '10 : SAH Commons',
 * '11 : Commons Hub',
 * '12 : SocSci Commons',
 * '13 : STEM Commons'
 */

// Hide some networks & post types from search facets.
add_filter( 'ep_bp_show_network_facet_3', '__return_false' ); // AJS.
add_filter( 'ep_bp_show_network_facet_5', '__return_false' ); // CAA.
add_filter( 'ep_bp_show_network_facet_8', '__return_false' ); // ARLIS.
add_filter( 'ep_bp_show_network_facet_11', '__return_false' ); // HUB.
add_filter( 'ep_bp_show_network_facet_12', '__return_false' ); // SOCSCI.
add_filter( 'ep_bp_show_network_facet_13', '__return_false' ); // STEM.
add_filter( 'ep_bp_show_post_type_facet_post', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_page', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_attachment', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_forum', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_bp_doc', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_event', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_bp_docs_folder', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_elementor_library', '__return_false' );
add_filter( 'ep_bp_show_post_type_facet_e-landing-page', '__return_false' );
```

See: https://github.com/MESH-Research/hc-custom/commit/15a91ed4b16c8d4c0e4a879469f9912d2a0d765a
