### ISSUE TITLE
WordPress importer not importing media

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#216]
Tried two tests on development: 
https://testmsutoolkit.hcommons-dev.org/ (actual site: https://instructortoolkit.msu.hcommons.org/)

https://testimportbr1.hcommons-dev.org/ (actual site:  https://sustaining.hcommons.org/)

[XML export files](https://app.zenhub.com/files/19561322/df912a9f-217b-4671-ac83-02c8c1932d3a/download)

Errors out when importing media. On the import of the MSU Commons Instructor Toolkit got the following errors:

Failed to import Media “Beaumont Tower”
Failed to import Media “MSU-commons-logo”
Failed to import Media “MSU-commons-toolkit-logo copy”
Failed to import Media “Beaumo2500x725”
Failed to import Media “Beaumo1600”
Failed to import Media “beaumontsm”
Failed to import Media “BeaumontTower1900”
Failed to import Media “cropped-Beaumo1600.jpg”
Failed to import Media “cropped-Beaumo1600-1.jpg”
Failed to import Media “msu commons home”
Failed to import Media “msu commons home”
Failed to import Media “MSU Commons Groups”
Failed to import Media “MSU Commons Registration”
Failed to import Media “MSU Commons Instructor Toolkit [PDF]”

This is new since the upgrade. Previous imports seemed to work fine.

**Comment by mikethicke** [comment]
This is perhaps specific to curl not being able to connect to hcommons.org from hcommons-dev.org.

$ curl https://hcommons.org/app/uploads/sites/1002459/2021/09/BeaumontTower.jpg times out from dev but works from my local machine.

**Comment by mikethicke** [comment]
Media import is working for non-hcommons sites.

For large sites or large media files timeouts might be an issue. In that case, we can run the importer through WP CLI.
