### ISSUE TITLE
User has no role on registration -- DEV

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#222]
Re-enrolled hctester40 this morning to test and he was enrolled with no role: 

https://hcommons-dev.org/wp-admin/user-edit.php?user_id=1030428&wp_http_referer=%2Fwp%2Fwp-admin%2Fusers.php%3Fs%3Dhctester40%26action%3D-1%26new_role%26bbp-new-role%26bbp-bulk-users-nonce%3D67375b896c%26bp_change_type%26bp-bulk-users-change-type-nonce%3Df55628c9be%26paged%3D1%26action2%3D-1%26new_role2%26bbp-new-role2%26bp_change_type2

All "join group" buttons are grayed out.

**Comment by mikethicke** [comment]
Retest

**Comment by bjr70** [comment]
Tried enrolling hctester20 and this is still happening. 

https://hcommons-dev.org/wp-admin/user-edit.php?user_id=1030430&wp_http_referer=%2Fwp-admin%2Fusers.php%3Fs%3Dhctester20%26action%3D-1%26new_role%26bbp-new-role%26bbp-bulk-users-nonce%3D3a23c2a90a%26bp_change_type%26bp-bulk-users-change-type-nonce%3D538b017726%26paged%3D1%26action2%3D-1%26new_role2%26bbp-new-role2%26bp_change_type2

No role.

**Comment by mikethicke** [comment]
I successfully enrolled a new user who picked up the correct HC role.

It might be the case that provisioning isn't happening quickly enough with the COmanage updates, so the user roles aren't ready by the time a user logs in for the first time?

One thing to check is whether a user's HC role gets added on *second* login if it doesn't initially. There is code that should check this on each login.

**Comment by mikethicke** [comment]
@bjr70 We should maybe test this again next week.

**Comment by bjr70** [comment]
I believe this is fixed.
