### ISSUE TITLE
Add HC ID to user Leonardo Flores's account

### ISSUE THREAD

**Issue by katknow** [MESH-Research/commons#225]
User Leonardo Flores (https://registry.hcommons.org/registry/co_people/index/Search.givenName:Leonardo/Search.familyName:Flores/co:2) would like to add an HC ID and password to his account as he no longer has access through MLA.

**Comment by mikethicke** [comment]
HCID leonardoflores has been added. The user should be contacted and given the following instructions:

Go to hcommons.org and click on Log in.
Click on HC.
Do not enter Username/Password.
Click on Forgot password?
On the screen presented, enter Username (leonardoflores) and press Search.
The email associated with this username will be sent a code. Retrieve that code from your email and enter it in the box.
You can then change the password.
After that you will be logged out and will need to goto hcommons.org to log in.

**Comment by katknow** [comment]
Emailing him now

**Comment by bjr70** [comment]
User notified.
