### ISSUE TITLE
Can no longer add events to calendar in the Learning Space theme

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#230]
In testing creating sites Kristen and I have found a discrepancy between the theme on HC and on MSU-C. This same issue exists on production.

On HC there is no option under "New" to enter a new event: https://hctester100-rosie.hcommons-dev.org/

On MSU-C that link : https://bonnie-rosiemsu.msu.hcommons.org/

It looks like there's a plugin missing on hc-dev that exists on msu-c. 

On MSU Commons the only place to add an event is that top bar under new. Events do not exist in the left-hand nav bar in wp-admin. Is there a way to add them there as well? 

Rosie Test is hctester100.

**Comment by mikethicke** [comment]
Learning space theme developed by MLA. Pass it off to MLA's developer?

**Comment by adonlon** [comment]
I'm not sure why the toolbar is different across networks, but the functionality is there. I was able to add an event on the test site on HC. This post gives instructions on how to do so via wp-admin: https://learningspace.hcommons.org/assignment/create-an-event/.

**Comment by mikethicke** [comment]
Should do some investigation about what's going on here.

**Comment by mikethicke** [comment]
This appears to be working. Tested on DEV and PROD with test user.
