### ISSUE TITLE
January WordPress Updates

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#231]
Note: This issue is for doing the updates and testing them. If issues arise in testing they should be tracked separately and be set as dependencies for this issue.

Tasks:

- [ ] Update WordPress on Dev
- [ ] Minor Plugin Updates on Dev
- [ ] Minor Theme Updates on Dev
- [ ] Preliminary Testing (test individual updates) (Do MESH-Research/commons#202 at the same time)
- [ ] Major Plugin Updates on Dev
- [ ] Major Theme Updates on Dev
- [ ] Final Round of Testing
- [ ] Deploy to Production

## WordPress

5.8.1 -> 5.8.3

## Plugins

See also: https://app.zenhub.com/workspaces/humanities-commons-61143609f268f000196abf18/issues/mesh-research/commons/202

#### Minor

- autoptimize 2.9.2 -> 2.9.5
- black-studio-tinymce-widget 2.6.9 -> 2.7.0
- buddypress-docs 2.1.5 -> 2.1.6
- debug-bar-elasticpress 1.3 -> 2.1.0
- elasticpress 3.6.2 -> 3.6.6
- elementor 3.4.5 -> 3.4.8
- essential-addons-for-elementor-lite 4.9.4 -> 5.0.1
- events-made-easy 2.1.119 -> 2.2.46
- events-manager 5.12 -> 5.12.1
- mashsharer 3.7.9 -> 3.8.0
- multisite-plugin-manager 3.1.5 -> 3.1.6
- newsletters-lite 4.7.9 -> 4.7.9.6
- ninja-forms 3.6.3 -> 3.6.7
- siteorigin-panels 2.14.3 -> 2.16.0
- participants-database 1.9.7.7 -> 1.9.7.8
- post-types-order 1.9.5.7 -> 1.9.7
- printfriendly 4.1 -> 5.0
- redis-cache 2.0.21 -> 2.0.22
- redux-framework 4.3.1 -> 4.3.5
- so-css 1.4.0 -> 1.5.1
- so-widgets-bundle 1.24.0 -> 1.28.0
- tainacan 0.18.5 -> 0.18.7
- video-conferencing-with-zoom-api 3.8.14 -> 3.8.16
- wp-accessibility 1.7.9 -> 1.7.11
- wp-google-maps 8.1.17 -> 8.1.19
- wp-to-twitter 3.5.3 -> 3.5.4

#### Major
- commons-in-a-box 1.0.14 -> 1.3.1
- printfriendly 4.1 -> 5.0
- zotpress 7.2 -> 7.3 
    (Author has fixed issue where updates delete settings, should test and abandon our fork.)

#### Minor
- dispatch 4.9.13 -> 4.9.21
- hello-elementor 2.2.2 -> 2.4.1 
- poseidon 2.2.3 -> 2.3.5
- responsive 4.6.2 -> 4.7.1
- twentyeleven 3.7 -> 3.9
- twentyfourteen 3.1 -> 3.2
- twentyseventeen 2.7 -> 2.8
- twentysixteen 2.4 -> 2.5
- twentyten 3.3 -> 3.5
- twentythirteen 3.3 -> 3.4
- twentytwelve 3.3 -> 3.5
- twentytwenty 1.7 -> 1.8
- twentytwentyone 1.3 -> 1.4

#### Major
- radcliffe 1.30 -> 2.0.1
- twentyfifteen 2.9 -> 3.0
- twentynineteen 1.4 -> 2.1
- vantage 1.17.2 -> 1.19.4

## References

- [Wordpress Releases](https://wordpress.org/news/category/releases/)
- [CBOX Changelog](https://github.com/cuny-academic-commons/commons-in-a-box/blob/master/readme.txt)
    - 1.3.1
        - BuddyPress 9.1.1, BuddyPress Group Email Subscription 4.0.1, Invite Anyone 1.4.2
        - Improved compatibility with PHP 8.0+.
    - 1.3.0
       - Updated plugins (Classic): BP Reply By Email 1.0-RC10, BuddyPress 9.0.0, BuddyPress Docs 2.1.6, BuddyPress Docs Wiki 1.0.11, External Group Blogs 1.6.2
       - Compatibility with WordPress 5.8 and BuddyPress 9.0.0.

Note: Need to develop procedure for monitoring and doing regular updates of themes / plugins not available through WordPress.org

**Comment by mikethicke** [comment]
@bjr70 Updates have been made on dev and are ready for testing.

**Comment by bjr70** [comment]
I'm having an issue with the print friendly plugin. When trying to print or PDF I get this: 

Ack! Print technology timed-out while trying to connect to this page.Try again. Reload the page.This page requires the PrintFriendly & PDF Browser Extension.Install Browser Extension (click the button below)Go back to the original page and use the browser extension.The Browser Extension is more powerful, faster, and easier to use, plus will not generate this error.Learn more.
PrintFriendly & PDF Chrome ExtensionPrint Friendly & PDF Button for FireFox, Chrome, iPad/iPhone, Internet Explorer, and Safari

Tried it on this page https://kendraprestonleonard.hcommons-dev.org/libretti/ and this page https://dianaprince.hcommons-dev.org/zotero/. 

This seems to suggest it only works on "public" pages so I wonder if the vpn is stopping it from working. https://wordpress.org/support/topic/browser-extension-required/. Thoughts?

**Comment by bjr70** [comment]
https://mlabib.mla.hcommons-dev.org/mla-bibliography-submission-form/ -- form "publication type" does not recognize that "scholarly web site" (the last option) is selected. Refuses to submit. Other types work.

**Comment by bjr70** [comment]
Theme twenty-nineteen isn't in the list of themes I can choose from as a non-privileged user.

**Comment by bjr70** [comment]
@katknow was able to replicate the issue on this form: https://mlabib.mla.hcommons-dev.org/mla-bibliography-submission-form/

**Comment by bjr70** [comment]
The rest of the updates look OK to me.

**Comment by bjr70** [comment]
@leekristmsu has finished testing and it looks like we've just got the couple of issues we've identified.

**Comment by mikethicke** [comment]
I updated PrintFriendly on production and confirmed that it is working correctly.

**Comment by mikethicke** [comment]
The MLA bibliography issue is just MESH-Research/commons#156. Required fields are required regardless of whether they are visible. The scholarly website type does not have a File Upload field, but this field is required for other types, and so it is required even though it is hidden. The issue exists on production.

**Comment by mikethicke** [comment]
Updates made on production.

Twentynineteen theme installed and enabled on DEV.
