### ISSUE TITLE
Write Blog post explaining no embedding for Docs & PDFs

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#234]
We are getting rid of (non-functional) plugins for embedding PDFs and Google Docs.

Write a blog post explaining this change to users:

- Accessibility and usability concerns with embedding
- Alternatives
- Can request Google Doc embed via iframes if necessary.

**Comment by bjr70** [comment]
Draft blog post here: https://team.hcommons.org/?p=624&preview=true

**Comment by bjr70** [comment]
[Email to go with blog post](https://app.zenhub.com/files/19561322/3386ea1d-81d1-4614-84cd-3029c38472d6/download)

**Comment by bjr70** [comment]
[updated template](https://app.zenhub.com/files/19561322/59bcdb29-7bdf-469f-8a06-0d403e02fe64/download)

**Comment by mikethicke** [comment]
Posted: https://team.hcommons.org/2022/01/05/embedded-documents-in-websites-on-the-commons/
