### ISSUE TITLE
Handling of deposits held for review

### ISSUE THREAD

**Issue by kfitz** [MESH-Research/commons#236]
When a user makes a first CORE deposit, or a series of deposits without having a prior approved deposit, that deposit is put into the review queue. However, the deposit is immediately available, and it appears in the Activity feed (as well as in the places where the Activity feed is used, like in the Member page sidebar). In an ideal world:

1. Deposits should only appear in Activity once they reach a "published" state -- once they've been reviewed.

2. The actual files should be unavailable for download until "published."

This has not been much of a problem in the past, but with the increase in activity by bad actors, this additional shielding would be a good thing to have in place.

**Comment by mikethicke** [comment]
Should consult with Eric about this.

**Comment by ericknappe** [comment]
Yes, it's a little tricky because vetting the author will need to occur in multiple places and some work flow may change. This really should include the DOI status change from draft to findable as well.

**Comment by bjr70** [comment]
Closing as moot. Will be resolved by Invenio implementation.
