### ISSUE TITLE
Member elastic press search results 

### ISSUE THREAD

**Issue by adonlon** [MESH-Research/commons#237]
If you search for something that returns a member profile and multiple networks are selected, the same profile will appear multiple times (3 networks=3 profiles) in the search results. I don't believe this used to be the case. I think it should probably show the profile on the network where the search is taking place but I'm not certain how it was set before.

**Comment by mikethicke** [comment]
A change to how duplicates were calculated led to this issue recurring.

Fix: https://github.com/MESH-Research/elasticpress-buddypress/commit/1a570df419d8deb040702fb2a30739930af34be8
