### ISSUE TITLE
Domain mapping msu.hcommons.org to commons.msu.edu

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#239]
- Users who have existing sites created as [sitename].msu.hcommons.org do not work as [sitename].commons.msu.edu (try this one: https://introdh2021.commons.msu.edu/)
- If we were to update these sites to [sitename].commons.msu.edu would the existing links still work? Example: https://introdh2021.msu.hcommons.org to preserve existing links that have been posted?
- If they do, should we manually update these sites? If not, could they be mapped properly to preserve the links?

**Comment by mikethicke** [comment]
Steps to make domain change in production:

- fix domains of network blogs:
  - edit ```/dev-scripts/commons/rewrite-msu-site-domains.php``` with correct values for $old_domain and $new_domain. 
  - run with $dry_run = true
  - if everything looks good, run with dry_run = false
- nginx configuration (hcommons.conf):
  - Change server_name line: ```server_name ~^(?<sitename>[\w-]+\.)?(?<subdomain>[\w-]+)\.msucommons-dev\.org$ msucommons-dev.org action.mla-dev.org *.action.mla-dev.org commons-dev.meshresearch.net;``` (correct for production)
  - Add (correct for production):
  ```
  if ( $subdomain = "msu" ) {
    rewrite ^ "https://${sitename}commons-dev.meshresearch.net$uri" permanent;
  }
  ```
  - reload nginx
- change values in .env
- other database fixes:
  - update wp_site table with correct domain for network
  - update domain of root blog in wp_blogs table
  - update home, siteurl in base site options table
- fix buddypress pages by removing them and readding them in buddypress settings page in wp-admin

**Comment by mikethicke** [comment]
Yeah it all needs to be corrected for prod

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
