### ISSUE TITLE
Discussions in public society groups should be visible

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#241]
Public society groups sometimes do not show posts to logged-out ( / non-society?) members.

> adonlon
> https://mla.hcommons.org/groups/general-linguistics/forum/ shows no posts when logged out; I can see the discussion forum posts when I'm logged in but I am not sure if non-privileged users do. I checked another forum and could see the discussion posts when logged out, so it isn't affecting every group... I'm checking with the staff member whether she was logged in or not when she tried to reach a discussion post (she'd originally clicked on a link from an email notification). 
> 
> 	
> mikethicke
> 9:23 AM
> So non-society members should be able to see posts in a society's public groups?
> 
> 	
> adonlon
> 9:25 AM
> Yes, the content of public groups has been public for anyone, member or not
> 
> 	
> mikethicke
> 9:25 AM
> 
> 
> 
> Got it.

**Comment by mikethicke** [comment]
There are a handful of forums where the bbpress forum post status has gotten out of sync with the buddypress group visibility. All of these are public groups with forums that do not have the post_status of 'publish':

hidden Narrative Empathy, Insecurity, and the Humanities
private CEDAR
private General Linguistics
private Carmen Martín Gaite in the 21st Century
hidden Careers for Humanists: A Job Search Workshop
hidden Humanities Commons – About
private Northern Irish Lit, Drama &amp; Visual Culture

These were probably groups where the visibility was changed at some point and the forum post_status was not changed to match.

```/dev-scripts/commons/fix_forum_visibility.php``` Fixes this issue on a one-time basis.

**Comment by mikethicke** [comment]
This took a long time to figure out!

**Comment by mikethicke** [comment]
These forums should now be visible on prod.

Eg: https://mla.hcommons.org/groups/general-linguistics/forum/

**Comment by bjr70** [comment]
This is working for me.

**Comment by adonlon** [comment]
Thanks for figuring it out!! Seems to be working from what I can see, too.
