### ISSUE TITLE
Request for new plugin addition - "page links to"

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#246]
Julie Libarkin has requested the addition of a new plugin: 

https://wordpress.org/plugins/page-links-to/

Description: "This plugin allows you to make a WordPress page (or post or custom post type) link to a URL of your choosing, instead of its WordPress URL. It also will redirect people who go to the old (or “normal”) URL to the new one you’ve chosen."

Julie's comments: "I was hoping you could add the “Page Links To” plugin to hcommons – this plugin allows a post or page to directly link to an external URL. This is very important for the community building/engagement aspects of the commons – we want to link to stories about our members."

This looks like it may be useful for some users, and it's a free plugin. On first glance I don't see anything troubling about it.

**Comment by kfitz** [comment]
I'm game to test this out. Let's install it on MSU Dev maybe and make sure it doesn't break anything.

**Comment by bjr70** [comment]
no longer needed
