### ISSUE TITLE
Editing Sites in MSU Commons

### ISSUE THREAD

**Issue by leekristmsu** [MESH-Research/commons#249]
When going to commons.msu.edu and trying to edit Sites, users were being treated as guests in the system even though they were logged in and were not being given the black bar of editing options across the top of the screen.

Going to msu.hcommons.org instead of commons.msu.edu resolved the issue.

Supports the need to migrate msu.hcommons.org sites to commons.msu.edu.

**Comment by mikethicke** [comment]
Once MESH-Research/commons#239 is complete this should be addressed without additional effort.
