### ISSUE TITLE
Convert legacy CORE subjects to FAST

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#256]
The current CORE subjects need to be converted to FAST subjects following Amaresh's schema below.

- [ ] Decide between Proposal 1 or Proposal 2 below for conversion
- [ ] Convert each deposit's subjects to the new format following steps below.

Amaresh's notes:

# Commons FAST Subject Conversion Notes
 
Date: 2022.01.19
 
## Steps for converting a subject in the system
Say we have a legacy subject ("Berlin") and its FAST replacement subject
("fst00123:Berlin, German Capital:Topic").
 
1. Add a new subject/taxonomy item for the FAST subject
2. Find all deposits that use the legacy subject and change them to use the FAST subject
3. Remove the legacy subject
 
We will have to do this for each of the current legacy subjects.
For some legacy subjects there is additional work to determine exactly
how to do the mapping:
- One to many mapping. One legacy subject maps to multiple FAST subjects.
- Legacy subject is ambiguous. "Composition" could refer to literature, music, art, etc.
- The mapping is unclear. We don't know what FAST subject a legacy subject should map to.
- Other issues
 
We also need to figure out the appropriate WP taxonomy related API calls to do the above steps.
Since we run a multi-network site we also need to make sure we are updating the correct set of WP tables
  - Look at Eric's wrappers around any taxonomy API calls that he uses
  - Figure out which database in WP holds the subject/taxonomy values and make sure to only modify that DB
  - Figure out where the subject values are stored for each deposit. This might be in multiple places
    - The WP _page_ corresponding to the deposit (basically how taxonomies are used in WP)
    - Any other places metadata is stored (Fedora, Solr, ???)
 
### Proposal 1
- Change all legacy subjects to the FAST subject format
  - Convert "Berlin" to "mla:Berlin:Legacy Subject"
- Now all subjects are in the same format
  - We still need to change the UI code to display them nicely
    ("**Berlin** (Legacy)") but the same code can act on both legacy and FAST subjects.
 
### Proposal 2
- Allow mixed subjects. That is some subjects will be
  in the legacy format ("Berlin") and others in the FAST format ("fst00123:Berlin, German Capital:Topic")
  - Change the UI code to check for the subject format and act accordingly
 
The advantage of both these approaches is that people from other disciplines can start making
deposits more quickly. We can then convert the legacy subjects to their _proper_ FAST values
on our own timeframe, without the conversion being a roadblock.

**Comment by bjr70** [comment]
I like proposal 2. I don't think it does any harm, and it does allow us to move more quickly and think through legacy deposits further.

**Comment by mikethicke** [comment]
Algorithm for subject conversion:

```
If legacy->FAST mapping is high confidence:
    If legacy subject is exact match of FAST subject (eg. History -> History):
        Convert the subject to FAST and do not create a corresponding keyword
    else :
        Convert the subject to FAST and create a keyword with the legacy subject
If legacy subject->FAST mapping is not high confidence:
    Convert the legacy subject into a keyword
    Create spreadsheet entry containing legacy subject, deposit title, deposit link, submitter name, submitter email 
        (spreadsheet entries grouped by deposit)
```

**Comment by amareshjoshi** [comment]
yes for the conversion algorithm, but different for the spreadsheet part.
I think we want to pull all subjects for all deposits that have at least one `low confidence` subject

```
For each deposit that has a low confidence subject:
  For each subject for that deposit
    Create a spreadsheet row containing:
      legacy subject
      conversion description (converted to FAST (with new subject) or demoted to keyword)
      deposit title
      deposit link
      submitter name
      submitter email 

Spreadsheet entries grouped by deposit and author)

```

**Comment by mikethicke** [comment]
I updated algorithm to remove spreadsheet line and add check for whether a deposit will be left with no subjects.

**Comment by mikethicke** [comment]
Confidence ranking: 

Confident > Unsure > Very Unsure > Ambiguous

**Comment by amareshjoshi** [comment]
Wrote 3 script to aid the migration:
- pull out data on changes to notify authors
- pull out and archive (text file) ALL metadata on ALL deposits in case of disaster recovery
- Convert subjects and keywords/tags to FAST
