### ISSUE TITLE
Test commons.msu.edu domain rewrites

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#287]
This issue is for testing MESH-Research/commons#239

The test environment for this is a bit weird. Here are how the URLs on dev correspond to those in production:

```
msu.hcommons.org => https://msu.msucommons-dev.org/
commons.msu.edu => https://commons-dev.meshresearch.net/
```

I think we need to test the following:

1. Do links to msu.msucommons-dev.org redirect correctly to commons-dev.meshresearch.net?
    1. Do links to commons-dev.meshresearch.net work correctly?
    2. Do links to msu.msucommons-dev.org/[some URI] redirect correctly?
    3. Do links to xxxxxxxx.msu.msucommons-dev.org/ redirect correctly?
    4. Do links to xxxxxxxx.msu.msucommons-dev.org/[some URI] redirect correctly?
    5. Do all of the above work for both http:// and https:// ?
2. Do logins persist correctly?
    1. If you login at https://commons-dev.meshresearch.net/ , are you able to create a new site and get to that site's dashboard?
    2. Are you able to login and get to the dashboard of an already existing site for which you have access? (This might require manually adding the test account as an administrator to an existing site)
    3. If you login at msucommons-dev.org/, and then go to msu.msucommons-dev.org, are you able to re-login and successfully do the above?

I think that would cover the most important use cases. I have an MSU test account, but I'm having some trouble connecting it to the Commons. So I think we can have a look at (1) right now, but will need to wait on getting the MSU test user connected properly to test (2).

Testing (1) takes a bit of work, as you will need to manually enter URLs in the browser's address bar. I think the best procedure is to find some sites on production (that are at least a month old, so we are sure they exist on dev) and translate those URLs into tests for (1i) - (1v).

To keep track, please record the URLs you test here and whether they worked or not.

**Comment by katknow** [comment]
1 seems to be working for me for the most part. I can't seem to access groups though on msu.msucommons-dev.org, though. 

Successfully tested on the following sites and, if applicable, their subpages with http and https:

https://msu.msucommons-dev.org/memebrs/kiknowles
https://msu.msucommons-dev.org/core
https://msu.msucommons-dev.org/deposits/item/hc:44329/

https://corawalby.msu.msucommons-dev.org/
https://introdh2021.msu.msucommons-dev.org/
https://hudsonr.msu.msucommons-dev.org/

Will working through 1, may take a stab at 2 on my own account.

**Comment by leekristmsu** [comment]
Number 2 seems to work smoothly for me, as well (all three steps above), using my own account.

**Comment by mikethicke** [comment]
I believe the groups issue identified by Katie has been addressed.

Still waiting on getting MSU test user access to the Commons.

**Comment by bjr70** [comment]
When I try to go to this group https://msucommons-dev.org/groups/test-group-1780135997/ it just returns me to the home page. The link from the groups page is pointing to that URL rather than commons-dev.meshresearch.net/groups/. Sites do seem to work OK.

**Comment by bjr70** [comment]
The group issue is an edge case. If you are on MSU Commons (commons.msu.edu) and view "My Groups" it will show you a list of all the groups you have membership in, including those on other Commonses (like Humanities or MLA Commons). If you click on any hidden or private groups that are housed on another Commons clicking the links will return you to the home page unless you are logged into both domains (hcommons.org and commons.msu.edu). This is the result of the cross-domain cookie issue. 

All MSU Commons groups and public Humanities Commons groups work as expected. We have decided not to try to fix this, as it's a very narrow set of circumstances. 

This is good to go to production.
