### ISSUE TITLE
Block-based themes to add to Commons dev for testing

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#290]
Block-based themes to test on dev for addition to the platform:
[Ocean WP](https://wordpress.org/themes/oceanwp/)
[Blockbase](https://wordpress.org/themes/blockbase/)
[Naledi](https://wordpress.org/themes/naledi/)
[Armando](https://wordpress.org/themes/armando/)

**Comment by mikethicke** [comment]
Themes added to DEV and enabled for all networks.
