### ISSUE TITLE
Redesign newsletter template to add "ways to give" and other information

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#291]
Incorporate Ways to Give page https://hcommons.org/ways-to-give/

**Comment by bjr70** [comment]
[Updated template with new button](https://viewstripo.email/e0e1e39b-895d-439f-a3ca-bbedb274176f1645466831444)

**Comment by mikethicke** [comment]
I like the support button!

This isn't something new, but I'm not sure about the repeated subject line.

**Comment by bjr70** [comment]
I don't see a duplicated subject line? ![emailtemplate.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/522665df-5c6a-479e-9e7c-26a52a8baa34)

**Comment by bjr70** [comment]
Templates for newsletters and email notifications have been created.
