### ISSUE TITLE
Recurring problems with users being unable to change emails

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#293]
Users are not able to change their emails when additional emails are added to COmanage:

- MESH-Research/hc-admin-docs-support#144
- MESH-Research/hc-admin-docs-support#137
- MESH-Research/hc-admin-docs-support#112 (possibly)

User's email addresses are stored in shib_email usermeta, set in humanities-commons/hc-simplesaml.php::hcommons_set_shibboleth_based_user_meta(). They are set based on $_SERVER['HTTP_MAIL']  variable ('mail' header).

**Comment by mikethicke** [comment]
The header is set on login. Typo in logging code.

**Comment by mikethicke** [comment]
Log entries will be generated in ```hcommons_error.log``` recording the value of shib_email when a user logs in and when a user visits the settings general page. Users should try re-logging in and check the log entries.

**Comment by mikethicke** [comment]
Icebox pending user feedback

**Comment by bjr70** [comment]
Two users are fixed, the other is non-responsive. I'm closing this for now. We can reopen if more users report issues.

**Comment by babaklar** [comment]
Reopening this as a new issue and linking back to this one. Sorry!
