### ISSUE TITLE
Testing of new block-based themes for use with WP 5.9

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#294]
Block-based themes to test on dev for addition to the platform:
Ocean WP
Blockbase
Naledi
Armando

Need to test themes to see compatibility and use, may need to provide documentation on how to use them.

**Comment by mikethicke** [comment]
@bjr70 I arbitrarily estimated this as an '8', but feel free to adjust. Might end up being more if all of us are doing testing.

**Comment by katknow** [comment]
I've been clicking around in the block-based themes and while I think they work I do think documentation may be helpful--I don't find them intuitive at all, but that may just be because I've been using the other version for so many years.
