### ISSUE TITLE
WordPress 5.9 update testing

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#299]

**Comment by bjr70** [comment]
We should test the upgrade first with existing themes. Then test with the new block-based themes.

**Comment by bjr70** [comment]
@mikethicke I'm logged in as Ferdinand Test and I invited him to a hidden group. When I click on the notification it doesn't take me to invites, it sends me to the home page instead: https://hcommons-dev.org/members/ferdinandtest/groups/invites/?n=1. Can't accept the invite to join.

**Comment by katknow** [comment]
I'm getting some weirdness with groups generally. I'm logged in, but I can't seem to access groups on either hcommons-dev.org or aseees.hcommons-dev.org, which my test user (hctester60) is supposedly a member of. It says I need to join, but I'm definitely logged in:

<img width="1141" alt="Screen Shot 2022-03-02 at 5 52 04 PM" src="https://user-images.githubusercontent.com/84726696/156463556-abd8a1ae-a942-42a4-b78f-013d0b3ac8e3.png">

<img width="1135" alt="Screen Shot 2022-03-02 at 5 51 37 PM" src="https://user-images.githubusercontent.com/84726696/156463560-7263a1c7-b23f-4f21-90c1-6deea5be89d3.png">

**Comment by mikethicke** [comment]
@katknow Hmm... I'm seeing the groups as Meghan:

![Screen Shot 2022-03-03 at 9.56.28 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/b6e842e3-84c7-4bcc-a4e9-37bad3c38a9d)

Can you confirm whether you see them now?

**Comment by mikethicke** [comment]
Oh, it's that you can't join them.

**Comment by katknow** [comment]
Yeah sorry should've been more clear it wants me to join, but I can't because I'm logged in and already registered as having joined it seems

**Comment by mikethicke** [comment]
@katknow Sorry, I'm still not following exactly what is going wrong. Can you create an issue for this? If you create a new issue, there is a Bug Report template you can fill out.

**Comment by katknow** [comment]
@mikethicke I can fill out a bug report, but I think the confusion stems from the fact you're getting a different screen than I am for HC--I'm not getting any of the join buttons even on HC:
![image](https://user-images.githubusercontent.com/84726696/156622094-050f346a-0744-4099-8d94-64edfb51b477.png)

**Comment by bjr70** [comment]
Another odd issue. When creating an event there's a textbox that is not editable. That textbox is not present on production. See this screenshot: ![venue and textbox.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/864329f1-ca2c-416a-999e-359e2b7efd5f)

**Comment by bjr70** [comment]
When I edited permissions for this doc to visible for logged in users the doc disappeared from the docs page. It's still in activity, and I can still click on it, but it's not visible from Docs https://hcommons-dev.org/docs/second-document/.

**Comment by katknow** [comment]
Also, while trying to mess around with the CORE issue I noticed the "Share & Preserve Your Work" button and the link & button under "Here to Share Your Work?" on the right homepage don't do anything. The "Discover OA scholarship" does work. I guess the short version is that the upload form isn't accessible from anywhere.

**Comment by mikethicke** [comment]
@bjr Can you make issues for the event textbox and doc permissions problems?

**Comment by bjr70** [comment]
Issues resolved. Moving to production 3/14.
