### ISSUE TITLE
Build Sustaining > Policies

### ISSUE THREAD

**Issue by kfitz** [MESH-Research/commons#316]
Revise policies section of Sustaining site to include:

- Commons bylaws
- Terms of Service
- Privacy Policy
- Guidelines for Participation?

**Comment by bjr70** [comment]
This also looks good. I wonder if we should update the links in the footer to point to these so that we don't have to try to remember to do updates in both places?

**Comment by kfitz** [comment]
YES, definitely! I want these docs to live in ONE place if at all possible!
