### ISSUE TITLE
Groups not appearing for Meghan Test (hctester60) in HC

### ISSUE THREAD

**Issue by katknow** [MESH-Research/commons#319]
On my computer, I am unable to join or create groups from the hctester60 account

**To Reproduce**
1. Login as Meghan Test (hctester60)
2. Click on 'Groups'
3. No join/create groups button; asks to join even though I have joined

**Expected behavior**
I expected to be able to join and create groups on HC.

**Context**
Does this bug on production, development, or both?
- [ X] Tested on development instance
- [ X] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**
![image](https://user-images.githubusercontent.com/84726696/156624520-26af79fe-14b7-48ac-8e69-5b1fda189169.png)

**Additional context**
@mikethicke didn't seem to replicate the issue on his computer

**Comment by mikethicke** [comment]
Thanks @katknow . This is weird. I tried logging in again and still see the Join Group, etc. buttons. I rolled back BuddyPress to an earlier version due to the issue Bonnie encountered. It's possible this is related to your issue? Could you try one more time with Meghan?

**Comment by katknow** [comment]
@mikethicke I think it might've been a browser issue. It seems to be working today. Thank you!

**Comment by mikethicke** [comment]
Good to hear! Might have been a weird browser / login issue. Might also have been some weird BuddyPress interaction with the new version.
