### ISSUE TITLE
Random text box appearing in event creation screen

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#321]
**Describe the bug**
Another odd issue. When creating an event there's a textbox that is not editable. That textbox is not present on production. See this screenshot: ![venue and textbox.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/864329f1-ca2c-416a-999e-359e2b7efd5f)

**Expected behavior**

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
The 'textbox' was actually a broken Google maps embed. Can be disabled in Events Organizer settings.
