### ISSUE TITLE
Digital Pedagogy MLA site broken

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#323]
https://digitalpedagogy.hcommons-dev.org/keyword

From @adonlon on Mattermost: "Not sure if GraphQL was upgraded or something else... I think this was an issue at the last upgrade, too. @ericknappe may know more!"

**Comment by mikethicke** [comment]
Accidentally updated wp-graphql plugin on dev at some point. Rolled back to 0.7.0.
