### ISSUE TITLE
User Denys McDonald repeatedly stuck in confirmed

### ISSUE THREAD

**Issue by katknow** [MESH-Research/commons#325]
Date first reported: 3/23/2022
Date requested for completion:
Site: Humanities Commons
Area: account (registration)

Description
User Denys McDonald has made multiple attempts at registering for a Commons account and has been confirmed each time. I expunged the first few attempts, but left the one below for reference. The user has tried different email addresses/login methods and is confirmed each time.

Further details
COmanage: https://registry.hcommons.org/registry/co_people/index/co:2/search.mail:denysmcdonald%40outlook.com/op:search

**Comment by ericknappe** [comment]
User role in Comanage is still Confirmed. I've updated it

How to note from Trello days

Usually the user got some error and is partially setup. This procedure assumes that a wpid was created and some kind of authentication was performed (google, twitter, idpolr). If that's not the case expunge and contact the user to register again - sorry.

The role record is linked to the petition.
Go to the CO Person record and Edit the HC Role Attributes record.

Set Status to Active.
This will cause the CO Person Status to become Active and fix both the members and members:HC groups. 

Then click Autogenerate Identifiers.
This will create the missing COmanage hcid identifier.

Then Primary Grouper Deployment (GrouperProvisioner) and
Primary LDAP Deployment (LdapProvisioner)
Check LDAP for uid:, isMemberOf: and employeeNumber:

**Comment by bjr70** [comment]
Mike was able to fix Denys and he's now in!
