### ISSUE TITLE
MLA committee unable to add docs

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#327]
Two committees have had an issue with creating agendas and placing them in folders. There is video of this issue here: 

https://peralta.instructuremedia.com/embed/09c5d3a8-e73b-4976-a5d2-d928bf0d6602

Behavior: "The process seems to be completed after hitting Save, but no pop-up appears and the file doesn't show up in the selected folder."

The two committees are: 
- Committee on Academic Freedom and Professional Rights and Responsibilities; folder in docs 21–22 Materials
- Committee on Community Colleges; folder 2021–2022 Committee Documents

More details: 
I'm not sure what group Anne was experiencing the issue with, but I experienced it with CAFPRR. Both the chair of the committee, Erec Koch, and I were unable to successfully store a file in the Docs area. We tried with different files, both committee Word docs and a test doc that I created.

Here's what I did:

Hit Create new doc
Added title
Checked the box to indicate that this was a minor edit not requiring notification
Added attachment
Selected folder (for the test file I used the Roster folder under 20-21 materials to avoid cluttering the current year's docs)
Hit Save

I did not then see the usual pop-up that confirms the file was saved and the document was not listed in the folder or elsewhere in the group.

**Comment by bjr70** [comment]
Issue replicated switched to Anna Chang. Video of both attempts here: https://youtu.be/h8AkVmiDdAk.

**Comment by mikethicke** [comment]
This might have been fixed by: https://github.com/MESH-Research/hc-custom/commit/d9e63245b0d84289cb0fa085f6e0daccf7596f07

**Comment by bjr70** [comment]
Anna Chang has confirmed this is fixed.
