### ISSUE TITLE
CORE deposit - backdated embargoes

### ISSUE THREAD

**Issue by katknow** [MESH-Research/commons#335]
Date first reported: 4/15/2022
Date requested for completion:
Site: CORE
Area: deposit embargoes

Description
If a user backdates a deposit in the embargo field, the deposit is automatically pushed to publish rather than starting as pending for approval.

Further details
Example deposit: https://hcommons.org/deposits/item/hc:45249/

**Comment by bjr70** [comment]
Closing as moot. Will be resolved by the Invenio implementation.
