### ISSUE TITLE
Test COmanage-based membership passing

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#344]
Test that COmanage-based membership attributes are being passed correctly on login.

1) Turn off parsing of Grouper-based membership attributes in Humanities_Commons plugin on dev
2) Test to ensure that:
    - society membership is being passed correctly
    - group membership is being passed correctly
    - nested memberships are working correctly ( if society membership is expired, group membership should be as well even if it is active in COmanage)

**Comment by mikethicke** [comment]
Test procedure:

1) Add MLA groups to MLA test users file source (MLA_test_users_v2.csv) on DEV. Groups are in the AdHocAttribute.group column and are semicolon-delineated lists of MLA convention_code ids.
2) Ensure that groups for testing are set to 'managed' in WordPress group settings.
3) Register test user, check that they are granted membership in correct groups.
4) Edit file source to remove test user from group
5) Re-sync Org Identity (how?)
6) Re-login as user, check that the user is no longer a member of the group.
7) Re-add user to group in file source, re-sync, check that they are again a member
8) Expire the user's membership by setting valid_through to a time in the past, re-sync
9) Confirm that the user is no longer a member of the group (or society)

**Comment by mikethicke** [comment]
Revised procedure: 

1) Test user group assignments are on Test Users spreadsheet
2) Ensure that groups for testing are set to 'managed' in WordPress group settings. (In WP Admin, Edit group, ensure "Manage Group Memberships" on right is set to 'Yes')
3) Expunge and delete test user.
4) Register test user, check that they are granted membership in correct societies and groups. Note that users who have expired memberships in COmanage should not be members of that society in WordPress or members of that society's groups. You can check society membership by looking for the society badge in their profile or in WP Admin. You can check group membership from the Groups | My Groups tab.
4) Find user in COmanage, delete the base group from the 'Groups' section. This is the group without the 'Humanities Commons:' prefix.
5) Re-login as user, check that the user is no longer a member of the group.
7) Re-sync the member from OrgID source. Go to User's Page. Under Organizational Identity, find the source (eg. MLA testUsers), click gear, then edit. Click View Organizational Identity Source Record. Click View Organizational Identity Source. Click Resync Org Identity From Source.
8) Re-login as the test user, ensure that they are again a member of the group.

Testing expiry:
  
1) Expire the user's membership by setting valid_through to a time in the past (This requires a developer, so ask Mike to do it)
2) Re-sync the user (step 7 above)
3) Confirm that the user is no longer a member of the group (or society)


Note: Currently only MLA is set up for this. Can add other societies for testing if necessary.

**Comment by bjr70** [comment]
Ferdinand did not pick up the committee that he should have. I was not able to join through MLA Commons, only HC. Not sure if this made a difference. 

![Ferdinand-groups.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/40324e2f-ddc3-4b5e-946d-5a53d1c4c638)

**Comment by mikethicke** [comment]
Sorry Bonnie---I wasn't thinking about this correctly. If the user doesn't use the MLA enrollment flow then it's not going to look at the correct file source on registration for picking up the groups.

I'll see tomorrow if I can get the MLA flow working correctly and I'll add test users to groups in other societies so we can test around the MLA issue.

**Comment by bjr70** [comment]
I've tried with Barty Test (hctester10) and the committee did not come through when registering on MLA.

**Comment by ericknappe** [comment]
<img width="951" alt="Screen Shot 2022-06-08 at 3 15 49 PM" src="https://user-images.githubusercontent.com/89542414/172698949-b271a77f-25e4-46f5-a4db-5fc9c1d06fe5.png">

IdMS seems setup correctly. The isMemberOf for the Pub Committee is in Comanage and being sent to HC.

**Comment by bjr70** [comment]
One thing of note: If a user has managed groups on two commonses - e.g. MLA and UP - they only get the group for the commons they registered through. We may want to revisit this later.

**Comment by bjr70** [comment]
One more scenario to think about: if someone has an existing HC account and then gets a job at a UP and is added to a managed group how would they get it if they're already registered. that could happen if someone joined in the director position at a UP.

**Comment by mikethicke** [comment]
@bjr70 

MESH-Research/commons#397 should make it so that group membership is synced regardless of what society the user is logging in from and address the problem where users sometimes didn't receive group membership on initial login.

**Comment by bjr70** [comment]
When registering on mla.hcommons-dev.org both hctester10 and hctester50 were returned to a blank page on successful registration. I had to clear cookies to log in as both users. I then expunged both users to try on HC vs. MLA.

When trying to register hctester50 through humanities commons it returned a message stating that the user was already member and set that attempt to the status "duplicate" when trying to set up a Google authentication. I can't find another user with that email address. I have seen this happen with users stuck in the LDAP, but the users used only Google auth, not an HCID. Have also seen stuck organizational identity records. 

Was not able to replicate the duplicate error with HCTester10, and did not receive a blank screen when registering hctester10 on Humanities Commons. Appears to be an issue with society roles.

**Comment by bjr70** [comment]
Barty did receive a notification that they'd been added to the correct MLA group, but when trying to visit the group does not recognize them.

![butamember.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/c384fb62-166c-4744-aafa-02136379aa30)

![notamember.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/25598fbc-611d-4286-9d72-384ad93f32b1)

**Comment by bjr70** [comment]
Was able to replicate with hctester50 on MLA. Was unable to register with UP Commons due to user being either expired or not present. Dave did not receive membership in the committee expected, and received the blank screen on registration. Had to clear cookies to log in and gain access to site.

**Comment by mikethicke** [comment]
I believe the registration->blank screen issue should be resolved. I'll add more detail in a separate issue.

**Comment by bjr70** [comment]
My testing has now been successful for both MLA and UP. Passing to @kfitz and @babaklar for final testing.
