### ISSUE TITLE
Create HCID for user Ivan Mouraviev

### ISSUE THREAD

**Issue by katknow** [MESH-Research/commons#359]
- [x ] Add to an appropriate Epic

**Username**
inzru
https://hcommons.org/members/inzru/

**Email Address**
 ivanmouraviev@gmail.com - preferred
originally registered for the account with imou692@aucklanduni.ac.nz

**coManage profile**
https://registry.hcommons.org/registry/co_people/canvas/13608

**Date Requested**
5/9/2022

**Additional context**
User previously had access via Google, but despite clearing cache/cookies, trying different & incognito browsers, he still cannot get into his account.

Developer documentation: [Add an HCID for existing user](https://github.com/MESH-Research/hc-docs/blob/main/user-administration.md#add-an-hcid-for-existing-user--allow-an-existing-user-to-login-with-wordpress-id)

**Comment by babaklar** [comment]
Email with user ID sent
