### ISSUE TITLE
Delete user's old site and replace

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons#369]
User account:  shandip 
Support team member: Larissa & Bonnie
 Date first reported: 5-17-2022 
Site: hcommons.org 
Area: Sites
Reported through: hello@hcommons.org

Previous correspondence 
"I had originally created the website domain of csasa.hcommons.org but deleted it when I wanted to start afresh. When I tried to create a new page with the same domain name, it told me it was in use. Is there anyway to change that as well?"

**Comment by mikethicke** [comment]
https://csasa.hcommons.org/ has been fully deleted and the user should be able to create a new site with this domain.

**Comment by babaklar** [comment]
Emailed user.
