### ISSUE TITLE
Menu item not showing on mobile

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons#370]
User account:  shandip
 Support team member:  Larissa & Bonnie
Date first reported: 5-17-2022 
Site: hcommons.org 
Area: Sites
Reported from: hello@hcommons.org

Description 
"My website that I am building at ssaha.hcommons.org. On the desktop version of the website (where I built the site), the menu options show up in the right hand corner of the screen. They do not, however, show up on a tablet or phone. Is there a way to change this? I am sort of stumped after looking at multiple options and instructions online."

**Comment by bjr70** [comment]
@mikethicke can you generate a list of who is using this theme?
