### ISSUE TITLE
Test WordPress 6.0 updates

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#390]

**Comment by mikethicke** [comment]
Updates on dev:

## WordPress

6.0

## Plugins

| Plugin | Version |
|---|---|
| akismet                                | 4.2.4          |
| autoptimize                            | 3.0.4          |
| avatar-privacy                         | 2.6.0          |
| beehive-analytics                      | 3.3.15         |
| elasticpress                           | 4.2.0          |
| elementor                              | 3.6.6          |
| essential-addons-for-elementor-lite    | 5.1.6          |
| event-organiser                        | 3.12.0         |
| events-made-easy                       | 2.2.86         |
| ewww-image-optimizer                   | 6.6.0          |
| feedwordpress                          | 2022.0222      |
| gd-bbpress-attachments                 | 4.3.1          |
| gutenberg                              | 13.4.0         |
| issuem                                 | 2.8.7          |
| mailpoet                               | 3.90.2         |
| mashsharer                             | 3.8.1          |
| ninja-forms                            | 3.6.11         |
| siteorigin-panels                      | 2.16.14        |
| participants-database                  | 2.1.5          |
| password-protected                     | 2.5.3          |
| pdfjs-viewer-shortcode                 | 2.1.7          |
| post-types-order                       | 1.9.9          |
| pressforward                           | 5.2.9          |
| printfriendly                          | 5.2.4          |
| redis-cache                            | 2.0.26         |
| remove-dashboard-access-for-non-admins | 1.1.5          |
| shibboleth                             | 2.4            |
| so-css                                 | 1.5.3          |
| so-widgets-bundle                      | 1.36.0         |
| tainacan                               | 0.18.10        |
| redux-framework                        | 4.3.14         |
| video-conferencing-with-zoom-api       | 3.9.3          |
| widget-importer-exporter               | 1.6            |
| woosidebars                            | 1.4.6          |
| wp-polls                               | 2.76.0         |
| wp-accessibility                       | 1.8.1          |
| wp-fail2ban                            | 4.4.0.4        |
| wp-google-maps                         | 9.0.0          |
| wp-job-manager                         | 1.36.1         |
| wp-to-twitter                          | 3.5.6          |
| google-sitemap-generator               | 4.1.5          |
| zotpress                               | 7.3.1.2        |

## Themes

| name            | update_version |
|-----------------|----------------|
| blockbase       | 2.0.38         |
| hitchcock       | 2.1            |
| responsive      | 4.7.4          |
| reykjavik       | 2.1.0          |
| twentyeleven    | 4.1            |
| twentyfifteen   | 3.2            |
| twentyfourteen  | 3.4            |
| twentynineteen  | 2.3            |
| twentyseventeen | 3.0            |
| twentysixteen   | 2.7            |
| twentythirteen  | 3.6            |
| twentytwelve    | 3.7            |
| twentytwenty    | 2.0            |
| twentytwentyone | 1.6            |
| twentytwentytwo | 1.2            |
| vantage         | 1.19.12        |

**Comment by bjr70** [comment]
Test plans here: https://drive.google.com/drive/folders/1qZqSyei7l61zWywpzmh2fDHcyCWqNuep?usp=sharing
