### ISSUE TITLE
Delete CORE deposits - user did not have permission to upload

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons#396]
User account: 7701Wahissa
Support team member: Larissa
Date first reported: 6/8/2022
Site: Humanities Commons
Area (CORE, profiles, sites, groups, account ): CORE

Description
The user did not have permission from his publisher to upload the three deposits below:
https://hcommons.org/deposits/item/hc:46539/
https://hcommons.org/deposits/item/hc:46531/
https://hcommons.org/deposits/item/hc:46529/

Steps to reproduce
Step-by-step procedure to reproduce issue, if available.

Previous correspondence
Paste any previous correspondence here

Further details
User also requested change to his user ID: [issue #240](https://app.zenhub.com/workspaces/humanities-commons-61143609f268f000196abf18/issues/mesh-research/hc-admin-docs-support/240)

**Comment by ericknappe** [comment]
All 3 deposits have been removed.
