### ISSUE TITLE
COAR Notify development plan template

### ISSUE THREAD

**Issue by kfitz** [MESH-Research/commons#399]
COAR has asked its implementation partners to fill out this [development plan template](https://docs.google.com/document/d/1aICz3yt2n-qqw3anRWlJdL2GUReg_m6QrvsH6d62cL8/edit). We'll need to detail each of the use cases, including tasks, dates, responsibilities, and estimated costs.

**Comment by kfitz** [comment]
Give me a thumbs up when you've had a chance to review the plan, so that I can pass it to Kathleen S. @bjr70 @mikethicke

**Comment by bjr70** [comment]
This looks good to me @kfitz.

**Comment by kfitz** [comment]
Template delivered to Kathleen S, with a note saying that it will no doubt still shift a bit.
