### ISSUE TITLE
When clicking on a user profile in the news feed the site throws a 504 error

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#400]
Does not matter if you're logged in or not. To replicate:

Visit the news feed. Click on the user name of anyone in the news feed and try to visit their profile. The site will throw a 504 error. Any attempt to go back to the home page will result in a 504.

**Comment by bjr70** [comment]
This occurs when visiting any member file from the members list as well.

**Comment by mikethicke** [comment]
The issue seems to persist between page refreshes and visiting other pages on the site.

**Comment by mikethicke** [comment]
The root cause of this appears to be a solr timeout related to a library server issue.

**Comment by bjr70** [comment]
This is fixed.
