### ISSUE TITLE
Final release of the NOVI plugin

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#407]
Complete final testing and release the Novi plugin for membership management.

**Comment by bjr70** [comment]
Plugin in testing. Looks good so far.

**Comment by bjr70** [comment]
I've checked a number of Novi records against the last flat file and everything looks as it should. I believe this is ready to launch. Week of August 8th?

**Comment by bjr70** [comment]
Emailed Cambria to alert her of potential 8/11 launch and confirm that hctester50@gmail.com was still in their system.

**Comment by bjr70** [comment]
hctester50@gmail.com is still active in Novi. We are good to go for testing production on rollout.

**Comment by ericknappe** [comment]
I'll double check, but I think the code is on place for this.

What's needed is configuration of an Org ID source and then adding that source to various enrollment flows in prod.

**Comment by ericknappe** [comment]
Comanage Org Id Source and Novi Server record configration is complete. Ready for cutover from flat file source to Novi plugin source:

To cutover: run a sync org sources using the current flat file source, get the count of active members, run the sync org sources using the novi plugin. If the count is close, cutover the  enrollment flows to use the new source. Some minor variation in membership count is expected.

**Comment by ericknappe** [comment]
Results of sync with flat file source and Novi source.

Flat file ARLISNA Commons members 410
Novi API ARLISNA Commons members 310

That difference is just too great to just cut over, I need to find some examples and determine possible reasons:
Is the flat file wrong?
Does the API get errors?

**Comment by bjr70** [comment]
I’ll contact Cambria. I do know that initially she was not including some staff and others in the flat file, so that could explain the discrepancy.

**Comment by bjr70** [comment]
@ericknappe Cambria is asking for us to provide an example of some names of people who appear in Novi but not the flat file. Can you run a list?

**Comment by ericknappe** [comment]
Several types of issues found.

Some members are no longer active but not removed by flat file updates

A member with multiple records in Novi needs to be corrected, please report to ARLIS
jevans@mfah.org

Plugin failed to find records that appear to be active, reporting to SCG
Plugin incorrectly identified records as duplicates, reporting to SCG

**Comment by ericknappe** [comment]
The following messages were returned when syncing the Novi Source with the Commons and can be passed to ARLIS for verification

Member Status is not active (expired) (ahunsaker@unr.edu)
Member Status is not active (expired) (amather@artic.edu)
Member Status is not active (expired) (anna.perricci@gmail.com)
Member Status is not active (expired) (ashleypeterson@library.ucla.edu)
Member Status is not active (expired) (baopar@syr.edu)
Member Status is not active (expired) (bigler@frick.org)
Member Status is not active (expired) (caetllonn@gmail.com)
Member Status is not active (expired) (emilykflood@gmail.com)
Member Status is not active (expired) (genevieve.beaudry@mcgill.ca)
Member Status is not active (expired) (heather_strelecki@aiga.org)
Member Status is not active (expired) (Jason.Przybylski@ithaka.org)
Member Status is not active (expired) (jawilliams3@vcu.edu)
Member Status is not active (expired) (jburns@cornell.edu)
Member Status is not active (expired) (jkarlan@itatti.harvard.edu)
Member Status is not active (expired) (jkflemin@iu.edu)
Member Status is not active (expired) (jodimikesell@gmail.com)
Member Status is not active (expired) (jreisman@pratt.edu)
Member Status is not active (expired) (katherine.a.borkowski@gmail.com)
Member Status is not active (expired) (kmast@email.arizona.edu)
Member Status is not active (expired) (ksalomon@getty.edu)
Member Status is not active (expired) (kstafford2@artic.edu)
Member Status is not active (expired) (libsjs@emory.edu)
Member Status is not active (expired) (Linda.duychak@wisc.edu)
Member Status is not active (expired) (marissafriedman@comcast.net)
Member Status is not active (expired) (mbrown6@pratt.edu)
Member Status is not active (expired) (mduffyce@syr.edu)
Member Status is not active (expired) (mollie.echeverria@gmail.com)
Member Status is not active (expired) (mpattuel@pratt.edu)
Member Status is not active (expired) (navapau@umich.edu)
Member Status is not active (expired) (olivera.nastic@gmail.com)
Member Status is not active (expired) (pschlott@pratt.edu)
Member Status is not active (expired) (RD@upress.ufl.edu)
Member Status is not active (expired) (s.hackney@pitt.edu)
Member Status is not active (expired) (sbutterill@ocadu.ca)
Member Status is not active (expired) (sdunlap@ucsd.edu)
Member Status is not active (expired) (shelley.roff@utsa.edu)
Member Status is not active (expired) (spswanz@umich.edu)
Member Status is not active (expired) (syan8@lsu.edu)
Member Status is not active (expired) (tatiana.bryant@gmail.com)
Member Status is not active (expired) (vizzylane@gmail.com)
Member Status is not active (expired) (ycortes@skidmore.edu)
Member Status is not active (non_member) (castro2@email.arizona.edu)
Member Status is not active (non_member) (catherine.derose@yale.edu)
Member Status is not active (non_member) (edunigan@getty.edu)
Member Status is not active (non_member) (epiola@librarycompany.org)
Member Status is not active (non_member) (Gaea.bogue@sjsu.edu)
Member Status is not active (non_member) (hannah.plank@gmail.com)
Member Status is not active (non_member) (hosford@alfred.edu)
Member Status is not active (non_member) (irenetortorella@gmail.com)
Member Status is not active (non_member) (juliapolyckoneill@gmail.com)
Member Status is not active (non_member) (mmilewski@toledomuseum.org)
Member Status is not active (non_member) (paula.farrar@ubc.ca)
Member Status is not active (non_member) (paula.hickner@uky.edu)
Member Status is not active (non_member) (pj27jones@yahoo.com)
Member Status is not active (non_member) (sarah.glasser@ithaka.org)
Member Status is not active (non_member) (vdeconin@ucsd.edu)
Member Status is not active (prospect) (angie.hurshman@gmail.com)
Record is flagged as inactive/deleted (arlis@minsky.com)
Record is flagged as inactive/deleted (dan.ruccia@dukeupress.edu)
Record is flagged as inactive/deleted (g-most@nga.gov)
Record is flagged as inactive/deleted (info@karnobooks.com)
Record is flagged as inactive/deleted (jevans@mfah.org)
Record is flagged as inactive/deleted (jvincennie@gmail.com)
Record is flagged as inactive/deleted (nick.curotto@vmfa.museum)
Record is flagged as inactive/deleted (ultan004@umn.edu)

**Comment by bjr70** [comment]
A tweak needs to be made to the plugin to prevent it from pulling deleted records in search. Ticket submitted to SCG.

**Comment by bjr70** [comment]
New issue created to deal with duplicate Novi records: https://app.zenhub.com/workspaces/humanities-commons-61143609f268f000196abf18/issues/mesh-research/hc-admin-docs-support/350
