### ISSUE TITLE
Investigate password management solutions

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#410]
Investigate password management solutions that comply with MSU policies.

**Comment by kfitz** [comment]
MSU IT does not have any solutions available for us. So we're going to have to figure out what we want to do and put it through the purchasing/IT readiness process...

**Comment by bjr70** [comment]
Another solution to investigate: https://itsfoss.com/padloc/

**Comment by kfitz** [comment]
I'm going to hand this project to Dimitris, who I know has been asking about it!

**Comment by tzouris** [comment]
Suggested we use Bitwarden Enterprise. IT readiness form already filed by Bonnie.
Advantages: SSO with Okta, self-hosting and complimentary family plan for each user.

**Comment by tzouris** [comment]
https://bitwarden.com/pricing/business/

**Comment by tzouris** [comment]
Closing this ticket since the investigation part is over.
