### ISSUE TITLE
Users lose user site permissions

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons#417]
We received an email from ARLIS/NA member Megan Macken that says:"I was updating the [ARLIS/NA Reviews site](https://reviews.arlisna.hcommons.org/) and all of a sudden it said I do not have access to edit the site, but I am the site admin." When I checked her admin permissions in Wordpress, it was showing she was a subscriber. We received the same message from a user yesterday--he was an admin of [ARLIS/NA Mountain West Chapter](https://mountainwest.arlisna.hcommons.org/) whose permissions were switched to subscriber. 

In both these cases, I've updated their permissions to be correct, but I am wondering if this is related to the grouper issues and [commons #415](https://app.zenhub.com/workspaces/humanities-commons-61143609f268f000196abf18/issues/mesh-research/commons/415).

**Comment by mikethicke** [comment]
I don't think this is a Grouper / COmanage issue. The associated groups are not managed groups. All that gets passed from COmanage are a user's group and society memberships---not their roles in particular groups, and nothing to do with sites.

Can we try to replicate this behavior on DEV? Ie. have an ARLISNA test user create a site, log out, and log back in?

Is it possible these are migrated sites and the ARLISNA users never actually had administrator access on the Commons sites?

**Comment by mikethicke** [comment]
We should also check what the roles are for existing users for ARLISNA sites on dev and prod.

**Comment by babaklar** [comment]
Okay, good to know about Grouper/COManage. I will try this with a test user on ARLIS/NA Commons dev. The users who contacted us have definitely made it sound like they had administrator permissions and then they lost access. However, this might be worth a follow up.

**Comment by babaklar** [comment]
We had another user report a similar issue, although this time it was an HCommons site. This is the user's message: "I have created a commons site [(Comprehensive Exam Notes)](https://jbrownexams.hcommons.org/), and set the privacy to admin only. I am logged into the commons, but now when I try and visit the site (through the my sites menu option) it tells me that the site is "Visible only to administrators of this site." How can I get access to my site again?"

In WP Admin, it was showing she was a "keymaster" on the site. I changed her permissions back to admin so she can edit it again, but this sounds similar to what the ARLIS/NA folks reported to us.

**Comment by babaklar** [comment]
Another user has contacted us for this issue on an HCommons site, and it's the same exact issue as what happened with the Comprehensive Exam Notes user. The user wrote: I would like to delete the website I started earlier this week ("[qctheatroscope.hcommons.org](https://qctheatroscope.hcommons.org/)") -- for some reason I stopped being able to edit the site, and so I launched a "regular" WordPress site instead with the same content. The site at hcommons should thus be deleted, but as I cannot edit it, I also cannot delete the site.

When I looked up the site in WP admin, it's showing the user is "keymaster" on the site. I am going to hold off on deleting the site temporarily in case additional checking needs to be done here. ![Screen Shot 2022-07-21 at 8.41.21 AM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/ff29f635-455b-40b3-83ba-c707c2b9fce9)

**Comment by babaklar** [comment]
I've just updated Mischa's permissions to administrator. The user followed up by email to say he doesn't want his site deleted since we've been able to modify his permissions for him.

**Comment by babaklar** [comment]
Two more instances of this issue in the last two days. In both cases, I've updated the permissions for these users so they are admins again. 

User: Ian Dunkle
Site: ianddunkle.hcommons.org
Site created: 2021/03/05
Role showing: none

User: Ann Mullaney
Site: verbalmask.hcommons.org
Site created: 2021/06/08
Role showing: none

**Comment by babaklar** [comment]
I've updated his permissions and emailed to ask if he was able to access this site between the 15th and when he emailed us. 

User name: Steve McCarty
Username: stevemccartyinjapan
Site: [japanned.hcommons.org/](https://japanned.hcommons.org/)
Site created: 2019-09-14
Role showing: none

**Comment by babaklar** [comment]
I've continued to add reports of this error to our "Permissions Victims" spreadsheet: [https://docs.google.com/spreadsheets/d/1nnZb_k_qVac-X1pO2jZbFFNxAH3tLlIHZ_5T3g9TLdY/edit#gid=0](https://docs.google.com/spreadsheets/d/1nnZb_k_qVac-X1pO2jZbFFNxAH3tLlIHZ_5T3g9TLdY/edit#gid=0)

I'm posting this user email here because it's a bit different from the others. This user is reporting he was able to edit his site on July 27 but lost permissions on the 28th, so not within the timeframe of the Wordpress update: 

I was able to edit my site yesterday ([https://josephkgordon.hcommons.org/](https://josephkgordon.hcommons.org/)), but cannot today. Even though I am logged in, the option to "edit" is not available on any of the pages. If I try to click on "edit my profile" from the drop-down menu in the top right hand corner of the screen, I get the message "sorry, you are not allowed to access this page."

**Comment by babaklar** [comment]
Unfortunately we've had our first case of a user's permissions changing again after I've updated them in Wordpress. Ian Dunkle emailed us this morning to say he doesn't have admin permissions on his site. Here's what the user said happened: "I logged in after you reset it, and I was able to access the dashboard for both sites. But sitting down to the edit the site now, I discovered that the dashboard for ianddunkle is once again unavailable."

When I checked his site permissions in Wordpress, it's showing "none" again. I am going to update his permissions back, but we'll need to investigate further. ![Screen Shot 2022-08-01 at 8.37.14 AM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/f7ba0d86-4584-43f5-a170-6ef8839fe35d)

**Comment by babaklar** [comment]
Another user (Amanda Winkler) also lost her permissions again and reported this via email. Like the other user, her role is showing as "none" again. I've reinstated her admin permissions.

**Comment by babaklar** [comment]
Ian Dunkle contacted us again because he lost his permissions _again_. This is the first instance of a user losing their permissions three times. This is what he sent today: 

I'm only just trying now, but the reset seems not to have worked. As before, when I navigate to my dashboard I can see both sites listed, but only my secondary site has a link to "Dashboard." I tried, of course, to get to the dashboard through the other means (including typing the url).

I reset his permissions today, and will continue to document these instances on our spreadsheet: [https://docs.google.com/spreadsheets/d/1nnZb_k_qVac-X1pO2jZbFFNxAH3tLlIHZ_5T3g9TLdY/edit#gid=0](https://docs.google.com/spreadsheets/d/1nnZb_k_qVac-X1pO2jZbFFNxAH3tLlIHZ_5T3g9TLdY/edit#gid=0)

**Comment by mikethicke** [comment]
So there is probably something going wrong in the login process, probably related to society management passing from COmanage / Grouper retirement.

**Comment by mikethicke** [comment]
This is possibly caused by users logging in while on their personal sites and having roles removed that were supposed to be for the main site.

Possible fix (switch to main network site before adjusting roles): https://github.com/MESH-Research/humanities-commons/commit/9186b6126a2249a121e52b198b898e2a5c7388bd
