### ISSUE TITLE
Replace MLA logo on MLA Commons

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#418]
Please replace the current logo with this version : ![New logo](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/4911281d-e69a-4c8d-99b5-fa4121d22bf5)

If you need it resized let BR know.

**Comment by bjr70** [comment]
Anywhere where there’s a logo. I realize now that it’s kind of all over the place, including this page: https://hcommons.org/societies/. I will swap it out there.

**Comment by mikethicke** [comment]
<img width="1255" alt="Screen Shot 2022-07-20 at 12 07 48 PM" src="https://user-images.githubusercontent.com/26980498/180030476-7876b06e-6b8f-4f52-b613-ea63539df7a4.png">

Replacing the logo in the content area with this logo is no problem, but shrinking it down to fit in the menubar is going to make it comically tiny. That logo is supposed to be 129px x 65px. It's totally the wrong aspect ratio. It would be slightly more feasible in the refreshed theme where the logo area is more flexible, but still probably won't work in its current form.

**Comment by bjr70** [comment]
Doh! Try this one. ![MLA_top_corner.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/5c9c0bf0-2157-49b1-b9c4-a33e553eb3e3)
