### ISSUE TITLE
Theme refresh - Update page template headings

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons#426]
Update the page template headings as part of the theme refresh on hcommons-2. dev and hastac.hcommons-staging.org

**Comment by mikethicke** [comment]
This should be working on hcommons-2.dev

**Comment by mikethicke** [comment]
@babaklar @bjr70 --- can you confirm that this looks right now?

**Comment by bjr70** [comment]
It does, it just needs to be carried over on HASTAC now.
