### ISSUE TITLE
ZipArchive not working correctly

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons#428]
**Describe the bug**

**To Reproduce**
1. In WP Admin, Go to 'Tools/Add Data Export Request' (can also be access through user email - there is one in the HC email inbox right now)
2. Click on 'Send Export Link'
3. After buffering, there is a message reading: "An error occurred while attempting to export personal data. Unable to generate personal data export file. ZipArchive not available." No user email is sent. The same happens when choosing "Download personal data" under the user's email address. 

**Expected behavior**
Should send email to user with data. 

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [x] Tested on production
- [x] Occurs on productions

**Screenshots**
Screenshot here![Screen Shot 2022-08-01 at 9.15.14 AM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/01dbdf7a-dbd3-41c0-9d99-55d7e2088654)

**Additional context**

**Comment by mikethicke** [comment]
This is probably a missing PHP module due to php 7.4 update.

See: https://www.php.net/manual/en/zip.installation.php

**Comment by mikethicke** [comment]
The ZIP extension for php 7.4 was not installed. This is now corrected and personal data export is functioning.
