### ISSUE TITLE
Add functionality to show/hide CORE deposits on profiles

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons#437]
Similar to other sections on the profile page, add functionality so users can show/hide section with CORE deposits. Once this is completed, I'll let the user who emailed us about removing his deposits know.

**Comment by bjr70** [comment]
It works! @babaklar does this work for you?

**Comment by babaklar** [comment]
I went onto my profile to test it, and my CORE deposit isn't showing up in that section of my profile at all. I can see it in the "Recent Commons Activity" area but not in the "Works Shared in CORE" section? Here's the link: [https://hcommons.org/members/babaklar/](https://hcommons.org/members/babaklar/)

**Comment by babaklar** [comment]
Tried deleting cookies and this fixed the error I mentioned about. Show/hide works as well. Contacted user.
