### ISSUE TITLE
CORE deposit not loading correctly

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons#447]
A [user](https://hcommons.org/members/markperkins/) alerted us because the metadata on his [CORE deposit](https://hcommons.org/deposits/item/hc:44701/) isn't loading. 

![Screen Shot 2022-08-18 at 9.46.29 AM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/598511f5-ab22-4bc9-b228-02b827685c1f)

**Comment by mikethicke** [comment]
The deposit seems to be loading correctly. Was it fixed, or was this a transient issue perhaps?

**Comment by babaklar** [comment]
It's working for me as well. Looks like some kind of transient issue. Emailed the user and closing this issue.
