### ISSUE TITLE
Discussion groups are showing usernames in HTML

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#461]
**Describe the bug**
![Screen Shot 2022-09-19 at 4.28.51 PM.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/1b5aa333-7fd1-472d-84b8-7e0524e185c0)

**To Reproduce**
1. Go to the discussion boards and click on any of them
2. Usernames are displayed as html links `
<a href='https://hcommons.org/members/betsysneller/'>Betsy Sneller</a>
6 months, 2 weeks ago`

**Expected behavior**
Usernames should appear as linked text. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [x] Occurs on productions

**Screenshots**

**Additional context**

**Comment by bjr70** [comment]
This is also happening on the development server: https://hcommons-dev.org/groups/library-information-science/forum/

**Comment by mikethicke** [comment]
This was caused by https://github.com/MESH-Research/humanities-commons/commit/3fd70e9cb1f1695dd7544695cdab89a75de31c42 . Added a check to stop links being added in forums, etc.
