### ISSUE TITLE
CORE deposits redirecting to home page

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#463]
**Describe the bug**
All CORE deposit links - on profiles and on the CORE browse page - are redirecting to the home page. 

**To Reproduce**
1. Click on a CORE deposit link
2. Site redirects to home page

**Expected behavior**
Clicking on a CORE deposit should take you to the deposit page. 

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
This appears to have been an issue with the library servers.
