### ISSUE TITLE
Blog author linking broken on Twenty Twenty

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#474]
See https://bonnie.hcommons.org/musings/. The link to the blog author profile is showing as html. 
![2022-10-24_09-50-56.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/03b88f59-db00-4c16-99ae-7c28ff6ff907)

**Comment by mikethicke** [comment]
Addressed by https://github.com/MESH-Research/humanities-commons/commit/c2b736450d0c3f9c1c20d8c45ba4705f38cef937
