### ISSUE TITLE
Creation of a "home" page on groups

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#477]
We'd like to look into enabling the use of a "Home" page on groups like the front page on [DH2020](https://hcommons.org/groups/dh2020/). @ericknappe how was this created, and would it be possible to build this into a feature all group admins could use?

![DH2020.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/317a18d0-ffd1-4c7d-a838-c5b963e307bc)

**Comment by mikethicke** [comment]
Group front pages are hardcoded page templates in ```boss-child/buddypress/groups/single```. I don't think there's an easy way to create frontend UI for these.
