### ISSUE TITLE
Add HASTAC as an org identity flow in CoManage

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/commons#480]
We received an email from an HCommons user who would like to gain access to HASTAC Commons. Add HASTAC to the org identity flow when enrolling new users in CoManage.

**Comment by mikethicke** [comment]
This is done, but for the flow to work the user would either need to be a former hastac.org user (in which case they should already be a HASTAC Commons user) or be manually added to the HASTAC Additional organizational ID source.

A better way is just to give the user the HASTAC role from their CO Person page.
