### ISSUE TITLE
Can the blog posts widget on the HASTAC home page feature author name as well as title?

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#482]
From Cathy D: Latest posts on the homepage section: because posts tend to sound so generic it would be great if the author’s name could also appear on the front page (a linked to the relevant post, not to the author profile), like a newspaper byline. Example: “Welcome to HASTAC Commons” by Cathy N. Davidson

**Comment by mikethicke** [comment]
In the better-late-than-never department, I have added author names to the HASTAC home page feed. ( @bjr70 / @zwhnz )
