### ISSUE TITLE
Digest emails coming from HASTAC Commons

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#485]
Daily digest emails sent on Nov 9 all came from hastac@hcommons.org with HASTAC Commons subject and headers.

Digest sent on Nov 7:

![Screen Shot 2022-11-09 at 9.53.53 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/af518558-abaf-49a9-bfb6-e80180854876)

Digests sent on Nov 9:

![Screen Shot 2022-11-09 at 9.54.48 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/6bca5d9a-be6a-4561-b782-8c723b360957)

![Screen Shot 2022-11-09 at 9.56.42 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/b8ebdc50-082f-4451-93e5-6d1211972621)

Note that styling is also different.

A configuration change of note is that SparkPost was set up for HASTAC Commons on Nov 8.

**Comment by ericknappe** [comment]
Assuming the preview we store is an accurate reflection of the emails that go out. HASTAC Commons only appears in the HASTAC preview we stored last night, but it's bigger than I would expect.

ubuntu@hcommons:/mnt/efs-logs$ ls -l digest_2022_11_09*
-rw-r--r-- 1 www-data www-data      70 Nov  9 04:50 digest_2022_11_09_ajs.html
-rw-r--r-- 1 www-data www-data  807637 Nov  9 04:50 digest_2022_11_09_arlisna.html
-rw-r--r-- 1 www-data www-data      70 Nov  9 04:50 digest_2022_11_09_aseees.html
-rw-r--r-- 1 www-data www-data      70 Nov  9 04:50 digest_2022_11_09_caa.html
-rw-r--r-- 1 www-data www-data 1752079 Nov  9 04:50 digest_2022_11_09_hastac.html
-rw-r--r-- 1 www-data www-data  382265 Nov  9 04:50 digest_2022_11_09_hc.html
-rw-r--r-- 1 www-data www-data  123828 Nov  9 04:50 digest_2022_11_09_mla.html
-rw-r--r-- 1 www-data www-data      70 Nov  9 04:50 digest_2022_11_09_msu.html
-rw-r--r-- 1 www-data www-data  131549 Nov  9 04:50 digest_2022_11_09_sah.html
-rw-r--r-- 1 www-data www-data  266930 Nov  9 04:50 digest_2022_11_09_up.html

**Comment by bjr70** [comment]
Fixed.
