### ISSUE TITLE
The attribute mail (email) not being provisioned to ldap at enrollment in DEV although it is configured in the provisioner. 

### ISSUE THREAD

**Issue by ericknappe** [MESH-Research/commons#501]
Example after enrollment on 10/29/22

dn: employeeNumber=hctester60,ou=people2,o=HC,dc=commons,dc=mla,dc=org
sn: Test
cn: Meghan Test
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: eduPerson
objectClass: eduMember
objectClass: voPerson
title;role-363256: Graduate Student, Digital Humanities
givenName: Meghan
o;role-363256: University Of Phoenix
employeeNumber: hctester60
employeeType;role-363256: member
uid: 104181779486931445844+google.com@commons.mla.org
eduPersonAffiliation;role-363256: member
isMemberOf: CO:members:all
isMemberOf: CO:COU:HC:members:all
isMemberOf: CO:members:active
isMemberOf: CO:COU:HC:members:active
voPersonStatus: Active
voPersonStatus;role-363256: Active

**Comment by mikethicke** [comment]
Suspending the "Email Address Elector" data filter allows emails to be provisioned.

**Comment by mikethicke** [comment]
SCG working on underlying issue. See: MESH-Research/hc-admin-docs-support#205 (PMO 979)
