### ISSUE TITLE
Layout Problems on Group Pages

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#74]
Tester (if different from issue creator): Anne
Site: UP Commons, other society commons
URL: https://up.hcommons-dev.org/groups/
Test Account: Ferdinand Test / anyone not a member of that society (?)
Area (CORE, sites, profiles, groups, general): groups
If issue discovered on dev, does it also exist on prod? Yes

**Describe the issue**
If you are not a member of a society, the formatting of the Groups page is incorrect (at least for societies that have private or restricted groups). After a few groups displaying normally, the following groups will be left-aligned and have bullets (incorrect list styling). It looks like there is a premature closing ```</ul>``` tag or something like that.

**To Reproduce**
1. Login as a user without society membership.
2. Go to a society page.
3. Click on 'Groups'

**Expected behavior**
Groups should all be formatted centered.

**Screenshots**
<img width="929" alt="Screen Shot 2021-08-16 at 3 08 56 PM" src="https://user-images.githubusercontent.com/26980498/129616816-a13c9903-7936-4e81-beaf-1b4d74ef9d62.png">

**Comment by mikethicke** [comment]
Should be fixed.

**Comment by bjr70** [comment]
Fixed!
