### ISSUE TITLE
Critical error on event creation

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#75]
Tester (if different from issue creator): Kathleen
Site: hcommons
URL: https://hcommons-dev.org/groups/pietrs-test-group/events/
Test Account: hctester30
Area (CORE, sites, profiles, groups, general): groups
If issue discovered on dev, does it also exist on prod? No

**Describe the issue**
When an event is created, WP reports a critical error. When the page is refreshed, the event has been created.

**Expected behavior**
The event should be created without an error.

**Comment by mikethicke** [comment]
I believe this is a BPGES issue caused by attempting to send out email notifications when creating an event.

The crash appears to happen in ass_send_email (/srv/www/commons/current/web/app/plugins/buddypress-group-email-subscription/bp-activity-subscription-functions.php).

Also, the crash doesn't occur if 'Silent Create' is checked prior to clicking Publish.

This code has been substantially rewritten in BPGES 4.0.0. I'd start by upgrading to that version. Also might be related to differences between prod and dev in how email notifications occur?

**Comment by mikethicke** [comment]
Potential fix for testing: https://github.com/MESH-Research/hc-custom/pull/149

**Comment by bjr70** [comment]
I tested this with Ferdinand Test on dev and it was fine, but when I tested it with Diana Test on dev in the Octopus group it threw an error "There has been a critical error on this website." Also tried with my superadmin account in the submarines group and got the same error. In the superadmin case the event was created even though it threw an error. https://hcommons-dev.org/groups/submarines/events/test-event-3/

**Comment by bjr70** [comment]
Tried to create an event in the Octopus Talk group under my bonnie ID and the same issue happened. Critical error but the event was created https://hcommons-dev.org/members/bonnie/events/new-test-event/

Creating an event outside a group works as expected. https://hcommons-dev.org/members/bonnie/events/event-no-group/

**Comment by mikethicke** [comment]
Sorry about that. I need a better process for staging multiple changes to the same repository for testing. Can you try again?

**Comment by bjr70** [comment]
Fixed!
