### ISSUE TITLE
Docs disappear when moved

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#76]
Tester (if different from issue creator): Kathleen
Site: hcommons
URL: https://hcommons-dev.org/groups/pietrs-test-group/docs/
Test Account: hctester30 (any non-superuser)
Area (CORE, sites, profiles, groups, general): groups
If issue discovered on dev, does it also exist on prod? No

**Describe the issue**
Moving docs around in folders sometimes makes them disappear to the user, though they are still visible to superadmins.

**To Reproduce**
Tried to move a doc out of a subfolder to the top level by selecting "None," but the doc disappeared from the group docs hierarchy altogether. Created a new doc and moved from a subfolder up to a folder, and then a folder to top level. 

**Expected behavior**
Moving docs should not affect their visibility.

**Comment by mikethicke** [comment]
It seems that sometimes moving a doc between folders can kick it into a pending state, which makes it invisible to normal users (who can only see published posts). Trying to figure out what is triggering this behavior.

**Comment by mikethicke** [comment]
I believe this is caused by Akismet flagging moved docs as spam. Disabling Akismet for buddypress docs (through a filter in humanities-commons plugin) seems to solve the issue.

**Comment by mikethicke** [comment]
humanities-commons/humanities-commons.php:

```
// Disable Akismet for BuddyPress docs. Docs are getting spammed when moved around in folders. --Mike 21-08-19
add_filter( 'bp_docs_use_akismet', function() { return false; } );
```

**Comment by mikethicke** [comment]
Rather than disable Akismet altogether, the following function disables it when docs are being moved:

[humanities-commons/humanities-commons.php](https://github.com/MESH-Research/humanities-commons/blob/285cc69cf114ca7177941a49b27b97468d455ed6/humanities-commons.php#L182)
```
/**
	 * Disable Akismet for BuddyPress docs when a doc is being moved.
	 *
	 * This is meant to address an issue where docs get spuriously marked as
	 * spam when being moved.
	 * @link https://github.com/MESH-Research/commons/issues/76
	 *
	 * Note: This disables Akisment whenever a doc is being moved, and doesn't
	 * check whether there are other changes. In theory you could avoid the spam
	 * filter by moving the doc in addition to whatever else you're doing, but
	 * this seems like it'd be a lot of trouble to go through.
	 *
	 * @see buddypress-docs/addon-akismet.php BP_Docs_Akismet::check_for_spam
	 *
	 * @author Mike Thicke
	 *
	 * @global $bp_docs The BP_Docs object. @see buddypress-docs/bp-docs.php
	 *
	 * @param array         $save_args   The arguments to be saved.
	 * @param BP_Docs_Query $bdq_object  The query object.
	 * @param array         $passed_args The arguments passed from the save
	 * request.
	 *
	 * @return array Pass through $save_args unchanged. This filter acts by
	 *               removing a lower priority filter if necessary.
	 */
	public function hcommons_disable_akismet_for_moving_docs( $save_args, $bdq_object, $passed_args ) {
		global $bp_docs;

		$folder_id          = intval( $_POST['bp-docs-folder'] );
		$existing_folder_id = bp_docs_get_doc_folder( $passed_args['doc_id'] );

		if ( $folder_id !== $existing_folder_id ) {
			remove_filter(
				'bp_docs_post_args_before_save',
				array( $bp_docs->akismet, 'check_for_spam' ),
				10
			);
		}

		return $save_args;
	}
```

**Comment by bjr70** [comment]
This appears to be fixed.
