### ISSUE TITLE
Group with discussion board giving error "This group does not currently have a discussion board."

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#79]
- [x] Add to an appropriate Epic.

Tester (if different from issue creator): Bonnie
Site: hcommons
URL: https://hcommons-dev.org/groups/mdp/
Test Account: Bonnie
Area (CORE, sites, profiles, groups, general): groups
If issue discovered on dev, does it also exist on prod? ? (Hard to replicate at all)

**Describe the issue**
Bonnie is logged-in. Is an admin of the group. Clicks on link to the discussion board, gets error "This group does not currently have a discussion board." But it does. This error does not happen for other accounts or other groups.

**Comment by bjr70** [comment]
I can replicate this in Firefox and Edge. This does seem localized to just this group, and just on dev. Maybe low priority.

**Comment by mikethicke** [comment]
Seems to be fixed by bbpress database upgrades.
