### ISSUE TITLE
Uploading CV to profile cancels other profile updates.

### ISSUE THREAD

**Issue by mikethicke** [MESH-Research/commons#86]
- [x] Add to an appropriate Epic.

Tester (if different from issue creator): Kristen
Site: hcommons
URL: https://hcommons-dev.org/members/leekrist/
Test Account: leekrist
Area (CORE, sites, profiles, groups, general): profiles
If issue discovered on dev, does it also exist on prod? Yes

**Describe the issue**
Original description: will not save CV upload or changes to profile if I try to make them all in the same session; tried multiple times (updated FF)

From Mike's testing: If you upload a CV when editing profile, the other profile changes are not processed.

**To Reproduce**
1. Edit user profile
2. Choose a file to upload in the CV section
3. Edit at least one other field
4. Click save changes
5. The CV is uploaded, but the other changes are reverted.

**Expected behavior**
You should be able to edit multiple fields in your profile and also upload a new CV in one pass.

**Note**

The UI here is also not great, as it isn't clear to user that to upload a CV you choose a file and then click 'Save Changes'. It also isn't clear that the upload has happened as the 'View file' link is vert subtle.

**Comment by mikethicke** [comment]
Should be fixed. See: https://github.com/MESH-Research/bp-attachment-xprofile-field-type/pull/2

I'm pretty sure this issue has existed for as long as uploading a CV has been available.

**Comment by bjr70** [comment]
Fix looks good.
