### ISSUE TITLE
MSU SSO Updates

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#87]
- [x] Add to an appropriate Epic

Date first reported: 8/4/2021
Date requested for completion: 8/28/2021
Site: MSU Commons, Humanities Commons
Area (CORE, profiles, sites, groups, account ): Login

**Description**
On Saturday, August 28, 2021, MSU IT will change the login experience for Shibboleth, Sentinel, and OAuth applications
This change will impact the look and feel of the login screen for all applications that use Sentinel, Shibboleth and OAuth applications to authenticate

Instructions and a link will be send the week of 8/9.

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**
https://trello.com/c/TBbKkdCJ/96-msu-sso-updates

**Comment by mikethicke** [comment]
No problems in testing. No action needed at this time.
