### ISSUE TITLE
Review of all "dead sites" on the Commons and creation of a website acceptable use policy

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#90]
- [x] Add to an appropriate Epic

Date first reported: Fall 2020
Date requested for completion: Fall 2021
Site: Humanities Commons
Area (CORE, profiles, sites, groups, account ): Sites

**Description**
Cull dormant sites. This project started in Fall 2020. We should probably do another database pull to update dates and reassess users to notify. 

[HCommons sites](https://docs.google.com/spreadsheets/d/1qYQ_mrsQFkPTHD4bhe4MskHcZwdMiYyh2wI7TECn_wA/edit#gid=1795345456)
[Non-HCommons sites](https://docs.google.com/spreadsheets/d/1KiS807v-ufx4qLcCmZS2CIb5_mzedDTR0euicTAMZrI/edit#gid=454391756)
[Proposed policy](https://docs.google.com/document/d/1XxnN6b-x80OqGakeXChPUNpCcWDha9c2ERG0-eOUGHE/edit)

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**
https://trello.com/c/cJ0u1sWq/50-review-of-all-dead-sites-on-the-commons-and-creation-of-a-website-acceptable-use-policy

**Comment by bjr70** [comment]
@mikethicke can we generate a new pull of sites that has these fields? https://docs.google.com/spreadsheets/d/1nORTy_aLi9cuoZaBNfd7BLX8aExxdfU0WcvcVEwQ0Hk/edit?usp=sharing -- I'll sort it based on date, I just need the raw pull.

**Comment by bjr70** [comment]
[First draft of email communications to site owners](https://docs.google.com/document/d/1Wp5nW1VfqdwX2SMNDGirvLmAqgrWqzZgkcTc26MZeGQ/edit?usp=sharing).

**Comment by mikethicke** [comment]
@bjr70 Link to updated inventory: https://docs.google.com/spreadsheets/d/1UOkbr5mTpLWNtYY4wjfsTSzSikhMx0vTOUbwG__q920/edit#gid=759893246

It's pretty ugly, but you asked for raw!

**Comment by bjr70** [comment]
Proposed sites for cull
[Individual](https://docs.google.com/spreadsheets/d/1MWsAI79O9gwl6whD-IeENUxS2FOJnG9F/edit?usp=sharing&ouid=103402489004334795755&rtpof=true&sd=true)
[Group](https://docs.google.com/spreadsheets/d/1b3_rvzoe_i6J9TQ35sQ2OMdoeNfWOokC/edit?usp=sharing&ouid=103402489004334795755&rtpof=true&sd=true)

**Comment by bjr70** [comment]
MLA sites sent to A. Donlon.

**Comment by bjr70** [comment]
[proposed form to send to users](https://docs.google.com/forms/d/e/1FAIpQLSeUFhtecUibJqaW4evgT-WRrkGycUb92ScXiGLmbKX20e5niA/viewform) and [proposed initial email for individual site owners](https://viewstripo.email/8a4b2249-e8db-4c6e-b685-2830dced81f01632243057824)

**Comment by mikethicke** [comment]
Email sent to users.

**Comment by bjr70** [comment]
Emails to go out this week.

**Comment by bjr70** [comment]
Review of sites complete, work to remove dormant sites in progress.
