### ISSUE TITLE
Add the new Website Policy to the "create a site" page on HC

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#91]
- [x] Add to an appropriate Epic

Date first reported: N/A
Date requested for completion: September 15, 2021
Site: All 
Area (CORE, profiles, sites, groups, account ): Sites

**Description**
Add the [MSU Commons website policy](https://commons.msu.edu/website-policy/) to HC. 
[HC Commons website policy](https://hcommons.org/website-policy/)

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**
https://trello.com/c/093YUSOK/66-add-the-new-website-policy-to-the-create-a-site-page-on-hc-and-msu-c

**Comment by mikethicke** [comment]
Acceptable use policy: https://commons.msu.edu/website-policy/

**Comment by mikethicke** [comment]
- [ ] Update acceptable use policy
- [ ] Make available on commons more generally, not just on MSU
- [ ] Show to users when creating a new site

**Comment by mikethicke** [comment]
Added to bottom of Create a Site page on HC and MSU
