### ISSUE TITLE
Elastic search not working properly

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#92]
- [x] Add to an appropriate Epic.

Tester (if different from issue creator): Anne Donlon
Site: MLA, HC
URL: mla.hcommons-dev.org / also on mla.hcommons.org
Test Account: Anne
Area (CORE, sites, profiles, groups, general): 
If issue discovered on dev, does it also exist on prod? 

**Describe the issue**
Elastic Search is not working correctly:

- Filters not working
- ES on MLA Commons does not show CORE deposits on HC
- Filters on elastic search aren't working. I tried on HC and MLA Commons, trying to filter to CORE deposits.

**To Reproduce**

**Expected behavior**

**Screenshots**

## Optional details, if they seem relevant

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
History on Trello card: https://trello.com/c/DRVFkPcE/93-elastic-search-not-working-properly

**Comment by mikethicke** [comment]
See: https://github.com/MESH-Research/elasticpress-buddypress/pull/9

**Comment by mikethicke** [comment]
Should be working now.

**Comment by bjr70** [comment]
This looks good to me. @adonlon can you check?

**Comment by adonlon** [comment]
A note that the update yesterday introduced some of the issues on dev to prod (this may be known/expected!)--in particular, there are results with CORE deposit file names that don't resolve to the deposit page. For example, searching Shakespeare on MLA Commons has a result (about five down) titled "shakespeare-transformed-copyright-copyleft-and-shakespeare-after-shakespeare.pdf" which links to https://mla.hcommons.org/humcore_deposit/hc17197/hc17198/ which doesn't resolve / redirects to the HC homepage.

**Comment by mikethicke** [comment]
Cleaning up issues, and splitting unaddressed problems into new issues:

## New Issues
- CORE deposit files showing in ElasticSearch results ([commons#210](https://app.zenhub.com/workspaces/humanities-commons-61143609f268f000196abf18/issues/mesh-research/commons/210))
- Discussion replies don't have titles in ElasticSearch ([commons#211](https://app.zenhub.com/workspaces/humanities-commons-61143609f268f000196abf18/issues/mesh-research/commons/211))
- Remove landing page filter in ElasticSearch results ([commons#212](https://app.zenhub.com/workspaces/humanities-commons-61143609f268f000196abf18/issues/mesh-research/commons/212))
- Committees should appear in ElasticSearch results ([commons#213](https://app.zenhub.com/workspaces/humanities-commons-61143609f268f000196abf18/issues/mesh-research/commons/213)) 

## Resolved
- Network facets appear to be working.
- Member profiles and groups appear in results.
- Private group discussions are no longer leaked.
