### ISSUE TITLE
Frontend A11Y remediation

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#94]
- [x] Add to an appropriate Epic

Date first reported: 
Date requested for completion: Winter 2022
Site: All
Area (CORE, profiles, sites, groups, account ): Full site

**Description**
There is a document from UARC that identifies issues with the interface of Humanities Commons that is likely to be across nodes, including MSU Commons.

See [Google folder](https://drive.google.com/drive/folders/1poRUpS_-ytNQ3Mt0JGtiHWowjpHFJLza)

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**
https://trello.com/c/MYliTuZb/32-frontend-a11y-remediation

**Comment by mikethicke** [comment]
Addressed by theme refresh and replacement projects.
