### ISSUE TITLE
Work with member council to appoint Tech Advisory and User Advisory committees

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#95]
- [x] Add to an appropriate Epic

Date first reported: 
Date requested for completion: Fall 2021
Site: HCommons
Area (CORE, profiles, sites, groups, account ): Governance

**Description**
Create both the user and technical advisory boards as mentioned on https://sustaining.hcommons.org.

[Users nominated for boards](https://docs.google.com/spreadsheets/d/1HmRY6DB2iKx6ezK5dfsy9XnvyNsoTLZPm0oC-F40Ga4/edit?usp=sharing)

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**
https://trello.com/c/jNdgU1O8/80-create-user-tech-advisory-committees

**Comment by bjr70** [comment]
First meeting set for 8/25 at 1pm.

**Comment by kfitz** [comment]
Council made some good suggestions for additions. Bonnie is reaching out to two of them. Meredith Hale wrote today to suggest that we look at U Maryland's AADHum folks for more possibilities.

**Comment by bjr70** [comment]
Reached out to the two nominated today.

**Comment by kfitz** [comment]
Comments received from council are positive. Let's go ahead and put together formal letters of appointment.

**Comment by kfitz** [comment]
I've drafted a boilerplate letter of appointment for these groups. @bjr70, would you revise as needed and send these out? https://docs.google.com/document/d/1LMyEoHaQL_rUy1-xAUaUc_99TDfH6WcOanrgnJJPAyQ/edit

**Comment by bjr70** [comment]
This looks good, K. I'll send them out.

**Comment by bjr70** [comment]
Appointment letters sent.

**Comment by bjr70** [comment]
Appointment letters sent.
