### ISSUE TITLE
Establish regular member council meeting schedule and agenda format

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/commons#96]
- [ ] Add to an appropriate Epic

Date first reported: 
Date requested for completion: Fall 2021
Site: All 
Area (CORE, profiles, sites, groups, account ): Governance

**Description**

**Steps to reproduce**
Step-by-step procedure to reproduce issue, if available.

**Previous correspondence**
Paste any previous correspondence here

**Further details**
Anything else we should know?

**Trello link (if moved from Trello)**

**Comment by kfitz** [comment]
Comments received from council on proposed times -- the first Tuesday of February, May, and October, at 9:00 am -- are positive. Can we create scheduled tickets that will appear on the first Tuesday of each January, April, and September reminding us to create and post the agenda? If not, I have scheduled items in Things that will pop up for me, and I can create tickets for each meeting as they do.

**Comment by mikethicke** [comment]
I don't think we can create recurring issues directly, but we could probably do something with IFTT to make it work. Might be worth making a request to the developers as well.

**Comment by kfitz** [comment]
Okay, cool. For now I'm just going to close this ticket and rely on my Things triggers to create new tickets for each upcoming meeting. We can get fancier later.
